/*
Navicat MySQL Data Transfer

Source Server         : local-mariadb
Source Server Version : 50540
Source Host           : localhost:3309
Source Database       : dhdc_ctable

Target Server Type    : MYSQL
Target Server Version : 50540
File Encoding         : 65001

Date: 2015-04-07 20:42:05
*/

SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for cicd9ttm_planthai
-- ----------------------------
DROP TABLE IF EXISTS `cicd9ttm_planthai`;
CREATE TABLE `cicd9ttm_planthai` (
  `code` varchar(7) NOT NULL DEFAULT '',
  `desc_r` varchar(255) DEFAULT NULL,
  `valid` varchar(1) DEFAULT NULL,
  `icd9cm` varchar(1) DEFAULT NULL,
  `icd10tm` varchar(1) DEFAULT NULL,
  `icd10tmd` varchar(1) DEFAULT NULL,
  `tm1` tinyint(1) DEFAULT NULL,
  `tm2` tinyint(1) DEFAULT NULL,
  `tm3` tinyint(1) DEFAULT NULL,
  `tm4` tinyint(1) DEFAULT NULL,
  `tmtype` tinyint(1) DEFAULT NULL,
  `last_update` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`code`),
  UNIQUE KEY `code` (`code`) USING BTREE
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records of cicd9ttm_planthai
-- ----------------------------
INSERT INTO `cicd9ttm_planthai` VALUES ('1007700', 'การบริบาลหญิงตั้งครรภ์ด้วยการนวดที่ศีรษะ', 'T', 'N', '', 'Y', '1', null, null, null, '1', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('1007701', 'การบริบาลหญิงตั้งครรภ์ด้วยการประคบที่ศีรษะ', 'T', 'N', '', 'Y', null, null, '1', null, '3', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('1007708', 'การบริบาลหญิงตั้งครรภ์ด้วยวิธีอื่นที่ศีรษะ', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('1007709', 'การบริบาลหญิงตั้งครรภ์ ไม่ระบุวิธีที่ศีรษะ', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('1007710', 'การบริบาลหญิงหลังคลอดด้วยการใช้ยาสมุนไพรที่ศีรษะ', 'T', 'N', '', 'Y', null, null, null, '1', '4', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('1007713', 'การบริบาลหญิงหลังคลอดด้วยการนวดที่ศีรษะ', 'T', 'N', '', 'Y', '1', null, null, '1', '1', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('1007714', 'การบริบาลหญิงหลังคลอดด้วยการประคบสมุนไพรที่ศีรษะ', 'T', 'N', '', 'Y', null, null, '1', '1', '3', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('1007748', 'การบริบาลหญิงหลังคลอดด้วยวิธีอื่นที่ศีรษะ', 'T', 'N', '', 'Y', null, null, null, '1', '4', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('1007749', 'การบริบาลหญิงหลังคลอด ไม่ระบุวิธีที่ศีรษะ', 'T', 'N', '', 'Y', null, null, null, '1', '4', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('1007768', 'การบริบาลทารกด้วยวิธีอื่นที่ศีรษะ', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('1007769', 'การบริบาลทารก ไม่ระบุวิธีที่ศีรษะ', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('1007810', 'การนวดด้วยยาหรือน้ำมันหอมระเหยที่ศีรษะ', 'T', 'N', '', 'Y', '1', null, null, null, '1', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('1007811', 'การนวดด้วยวิธีการแพทย์แผนไทยแบบราชสำนักที่ศีรษะ', 'T', 'N', '', 'Y', '1', null, null, null, '1', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('1007812', 'การนวดด้วยวิธีการแพทย์แผนไทยแบบเชลยศักดิ์ที่ศีรษะ', 'T', 'N', '', 'Y', '1', null, null, null, '1', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('1007818', 'การนวดด้วยวิธีการแพทย์แผนไทยแบบอื่นที่ศีรษะ', 'T', 'N', '', 'Y', '1', null, null, null, '1', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('1007819', 'การนวดด้วยวิธีการแพทย์แผนไทย ไม่ระบุรายละเอียดที่ศีรษะ', 'T', 'N', '', 'Y', '1', null, null, null, '1', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('1007820', 'การประคบด้วยสมุนไพรที่ศีรษะ', 'T', 'N', '', 'Y', null, null, '1', null, '3', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('1007821', 'การประคบความร้อนที่ศีรษะ', 'T', 'N', '', 'Y', null, null, '1', null, '3', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('1007822', 'การประคบความเย็นที่ศีรษะ', 'T', 'N', '', 'Y', null, null, '1', null, '3', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('1007830', 'การทาหรือชโลมด้วยยาหรือน้ำมันหอมระเหยที่ศีรษะ', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('1007838', 'การใช้ยาบำบัดวิธีอื่นที่ศีรษะ', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('1007839', 'การใช้ยาบำบัด ไม่ระบุวิธีที่ศีรษะ', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('1007888', 'หัตถการอื่น ระบุวิธีที่ศีรษะ', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('1007889', 'หัตถการอื่น ไม่ระบุวิธีที่ศีรษะ', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('1547700', 'การบริบาลหญิงตั้งครรภ์ด้วยการนวดที่ใบหน้า', 'T', 'N', '', 'Y', '1', null, null, null, '1', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('1547701', 'การบริบาลหญิงตั้งครรภ์ด้วยการประคบที่ใบหน้า', 'T', 'N', '', 'Y', null, null, '1', null, '3', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('1547708', 'การบริบาลหญิงตั้งครรภ์ด้วยวิธีอื่นที่ใบหน้า', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('1547709', 'การบริบาลหญิงตั้งครรภ์ ไม่ระบุวิธีที่ใบหน้า', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('1547710', 'การบริบาลหญิงหลังคลอดด้วยการใช้ยาสมุนไพรที่ใบหน้า', 'T', 'N', '', 'Y', null, null, null, '1', '4', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('1547713', 'การบริบาลหญิงหลังคลอดด้วยการนวดที่ใบหน้า', 'T', 'N', '', 'Y', '1', null, null, '1', '1', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('1547714', 'การบริบาลหญิงหลังคลอดด้วยการประคบสมุนไพรที่ใบหน้า', 'T', 'N', '', 'Y', null, null, '1', '1', '3', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('1547748', 'การบริบาลหญิงหลังคลอดด้วยวิธีอื่นที่ใบหน้า', 'T', 'N', '', 'Y', null, null, null, '1', '4', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('1547749', 'การบริบาลหญิงหลังคลอด ไม่ระบุวิธีที่ใบหน้า', 'T', 'N', '', 'Y', null, null, null, '1', '4', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('1547761', 'การบริบาลทารกด้วยการเขียนคิ้วที่ใบหน้า', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('1547768', 'การบริบาลทารกด้วยวิธีอื่นที่ใบหน้า', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('1547769', 'การบริบาลทารก ไม่ระบุวิธีที่ใบหน้า', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('1547801', 'การรมด้วยยาสมุนไพรที่ใบหน้า', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('1547810', 'การนวดด้วยยาหรือน้ำมันหอมระเหยที่ใบหน้า', 'T', 'N', '', 'Y', '1', null, null, null, '1', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('1547811', 'การนวดด้วยวิธีการแพทย์แผนไทยแบบราชสำนักที่ใบหน้า', 'T', 'N', '', 'Y', '1', null, null, null, '1', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('1547812', 'การนวดด้วยวิธีการแพทย์แผนไทยแบบเชลยศักดิ์ที่ใบหน้า', 'T', 'N', '', 'Y', '1', null, null, null, '1', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('1547818', 'การนวดด้วยวิธีการแพทย์แผนไทยแบบอื่นที่ใบหน้า', 'T', 'N', '', 'Y', '1', null, null, null, '1', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('1547819', 'การนวดด้วยวิธีการแพทย์แผนไทย ไม่ระบุรายละเอียดที่ใบหน้า', 'T', 'N', '', 'Y', '1', null, null, null, '1', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('1547820', 'การประคบด้วยสมุนไพรที่ใบหน้า', 'T', 'N', '', 'Y', null, null, '1', null, '3', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('1547821', 'การประคบความร้อนที่ใบหน้า', 'T', 'N', '', 'Y', null, null, '1', null, '3', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('1547822', 'การประคบความเย็นที่ใบหน้า', 'T', 'N', '', 'Y', null, null, '1', null, '3', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('1547830', 'การทาหรือชโลมด้วยยาหรือน้ำมันหอมระเหยที่ใบหน้า', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('1547838', 'การใช้ยาบำบัดวิธีอื่นที่ใบหน้า', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('1547839', 'การใช้ยาบำบัด ไม่ระบุวิธีที่ใบหน้า', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('1547888', 'หัตถการอื่น ระบุวิธีที่ใบหน้า', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('1547889', 'หัตถการอื่น ไม่ระบุวิธีที่ใบหน้า', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('1857762', 'การบริบาลทารกด้วยการดึงจมูกให้โด่งที่จมูก', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('1857768', 'การบริบาลทารกด้วยวิธีอื่นที่จมูก', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('1857769', 'การบริบาลทารก ไม่ระบุวิธีที่จมูก', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('1857831', 'การนัตถุ์ยาที่จมูก', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('1857838', 'การใช้ยาบำบัดวิธีอื่นที่จมูก', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('1857839', 'การใช้ยาบำบัด ไม่ระบุวิธีที่จมูก', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('2337708', 'การบริบาลหญิงตั้งครรภ์ด้วยวิธีอื่นที่ปาก', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('2337709', 'การบริบาลหญิงตั้งครรภ์ ไม่ระบุวิธีที่ปาก', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('2337710', 'การบริบาลหญิงหลังคลอดด้วยการใช้ยาสมุนไพรที่ปาก', 'T', 'N', '', 'Y', null, null, null, '1', '4', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('2337748', 'การบริบาลหญิงหลังคลอดด้วยวิธีอื่นที่ปาก', 'T', 'N', '', 'Y', null, null, null, '1', '4', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('2337749', 'การบริบาลหญิงหลังคลอด ไม่ระบุวิธีที่ปาก', 'T', 'N', '', 'Y', null, null, null, '1', '4', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('2337764', 'การบริบารทารกด้วยการใช้ยาสมุนไพรที่ปาก', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('2337768', 'การบริบาลทารกด้วยวิธีอื่นที่ปาก', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('2337769', 'การบริบาลทารก ไม่ระบุวิธีที่ปาก', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('2337832', 'การทำให้อาเจียนด้วยยาสมุนไพรที่ปาก', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('2337838', 'การใช้ยาบำบัดวิธีอื่นที่ปาก', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('2337839', 'การใช้ยาบำบัด ไม่ระบุวิธีที่ปาก', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('2357768', 'การบริบาลทารกด้วยวิธีอื่นที่ลิ้น', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('2357769', 'การบริบาลทารก ไม่ระบุวิธีที่ลิ้น', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('2357838', 'การใช้ยาบำบัดวิธีอื่นที่ลิ้น', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('2357839', 'การใช้ยาบำบัด ไม่ระบุวิธีที่ลิ้น', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('2367768', 'การบริบาลทารกด้วยวิธีอื่นที่เหงือก', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('2367769', 'การบริบาลทารก ไม่ระบุวิธีที่เหงือก', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('2367838', 'การใช้ยาบำบัดวิธีอื่นที่เหงือก', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('2367839', 'การใช้ยาบำบัด ไม่ระบุวิธีที่เหงือก', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('3027713', 'การบริบาลหญิงหลังคลอดด้วยการนวดที่เต้านม', 'T', 'N', '', 'Y', '1', null, null, '1', '1', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('3027714', 'การบริบาลหญิงหลังคลอดด้วยการประคบสมุนไพรที่เต้านม', 'T', 'N', '', 'Y', null, null, '1', '1', '3', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('3027748', 'การบริบาลหญิงหลังคลอดด้วยวิธีอื่นที่เต้านม', 'T', 'N', '', 'Y', null, null, null, '1', '4', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('3027749', 'การบริบาลหญิงหลังคลอด ไม่ระบุวิธีที่เต้านม', 'T', 'N', '', 'Y', null, null, null, '1', '4', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('3067768', 'การบริบาลทารกด้วยวิธีอื่นที่รักแร้', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('3067769', 'การบริบาลทารก ไม่ระบุวิธีที่รักแร้', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('3067838', 'การใช้ยาบำบัดวิธีอื่นที่รักแร้', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('3067839', 'การใช้ยาบำบัด ไม่ระบุวิธีที่รักแร้', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('4007711', 'การบริบาลหญิงหลังคลอดด้วยการรัดหน้าท้องที่หน้าท้อง', 'T', 'N', '', 'Y', null, null, null, '1', '4', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('4007713', 'การบริบาลหญิงหลังคลอดด้วยการนวดที่หน้าท้อง', 'T', 'N', '', 'Y', '1', null, null, '1', '1', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('4007714', 'การบริบาลหญิงหลังคลอดด้วยการประคบสมุนไพรที่หน้าท้อง', 'T', 'N', '', 'Y', null, null, '1', '1', '3', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('4007748', 'การบริบาลหญิงหลังคลอดด้วยวิธีอื่นที่หน้าท้อง', 'T', 'N', '', 'Y', null, null, null, '1', '4', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('4007749', 'การบริบาลหญิงหลังคลอด ไม่ระบุวิธีที่หน้าท้อง', 'T', 'N', '', 'Y', null, null, null, '1', '4', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('4007764', 'การบริบารทารกด้วยการใช้ยาสมุนไพรที่หน้าท้อง', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('4007768', 'การบริบาลทารกด้วยวิธีอื่นที่หน้าท้อง', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('4007769', 'การบริบาลทารก ไม่ระบุวิธีที่หน้าท้อง', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('4007810', 'การนวดด้วยยาหรือน้ำมันหอมระเหยที่หน้าท้อง', 'T', 'N', '', 'Y', '1', null, null, null, '1', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('4007811', 'การนวดด้วยวิธีการแพทย์แผนไทยแบบราชสำนักที่หน้าท้อง', 'T', 'N', '', 'Y', '1', null, null, null, '1', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('4007812', 'การนวดด้วยวิธีการแพทย์แผนไทยแบบเชลยศักดิ์ที่หน้าท้อง', 'T', 'N', '', 'Y', '1', null, null, null, '1', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('4007818', 'การนวดด้วยวิธีการแพทย์แผนไทยแบบอื่นที่หน้าท้อง', 'T', 'N', '', 'Y', '1', null, null, null, '1', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('4007819', 'การนวดด้วยวิธีการแพทย์แผนไทย ไม่ระบุรายละเอียดที่หน้าท้อง', 'T', 'N', '', 'Y', '1', null, null, null, '1', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('4007820', 'การประคบด้วยสมุนไพรที่หน้าท้อง', 'T', 'N', '', 'Y', null, null, '1', null, '3', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('4007821', 'การประคบความร้อนที่หน้าท้อง', 'T', 'N', '', 'Y', null, null, '1', null, '3', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('4007822', 'การประคบความเย็นที่หน้าท้อง', 'T', 'N', '', 'Y', null, null, '1', null, '3', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('4007830', 'การทาหรือชโลมด้วยยาหรือน้ำมันหอมระเหยที่หน้าท้อง', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('4007838', 'การใช้ยาบำบัดวิธีอื่นที่หน้าท้อง', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('4007839', 'การใช้ยาบำบัด ไม่ระบุวิธีที่หน้าท้อง', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('4027768', 'การบริบาลทารกด้วยวิธีอื่นที่สะดือ', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('4027769', 'การบริบาลทารก ไม่ระบุวิธีที่สะดือ', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('4117768', 'การบริบาลทารกด้วยวิธีอื่นที่ขาหนีบ', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('4117769', 'การบริบาลทารก ไม่ระบุวิธีที่ขาหนีบ', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('4557768', 'การบริบาลทารกด้วยวิธีอื่นที่ทวารหนัก', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('4557769', 'การบริบาลทารก ไม่ระบุวิธีที่ทวารหนัก', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('4557801', 'การรมด้วยยาสมุนไพรที่ทวารหนัก', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('4557850', 'การควักอุจจาระที่ทวารหนัก', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('4557851', 'การเหน็บยาที่ทวารหนัก', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('4557852', 'การสวนอุจจาระที่ทวารหนัก', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('4557858', 'การทำให้ถ่ายด้วยวิธีอื่นที่ทวารหนัก', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('4557859', 'การทำให้ถ่าย ไม่ระบุวิธีที่ทวารหนัก', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('5277717', 'การบริบาลหญิงหลังคลอดด้วยการนั่งถ่านที่อวัยวะสืบพันธุ์หญิง', 'T', 'N', '', 'Y', null, null, null, '1', '4', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('5907700', 'การบริบาลหญิงตั้งครรภ์ด้วยการนวดที่หลัง', 'T', 'N', '', 'Y', '1', null, null, null, '1', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('5907701', 'การบริบาลหญิงตั้งครรภ์ด้วยการประคบที่หลัง', 'T', 'N', '', 'Y', null, null, '1', null, '3', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('5907708', 'การบริบาลหญิงตั้งครรภ์ด้วยวิธีอื่นที่หลัง', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('5907709', 'การบริบาลหญิงตั้งครรภ์ ไม่ระบุวิธีที่หลัง', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('5907710', 'การบริบาลหญิงหลังคลอดด้วยการใช้ยาสมุนไพรที่หลัง', 'T', 'N', '', 'Y', null, null, null, '1', '4', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('5907713', 'การบริบาลหญิงหลังคลอดด้วยการนวดที่หลัง', 'T', 'N', '', 'Y', '1', null, null, '1', '1', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('5907714', 'การบริบาลหญิงหลังคลอดด้วยการประคบสมุนไพรที่หลัง', 'T', 'N', '', 'Y', null, null, '1', '1', '3', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('5907748', 'การบริบาลหญิงหลังคลอดด้วยวิธีอื่นที่หลัง', 'T', 'N', '', 'Y', null, null, null, '1', '4', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('5907749', 'การบริบาลหญิงหลังคลอด ไม่ระบุวิธีที่หลัง', 'T', 'N', '', 'Y', null, null, null, '1', '4', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('5907810', 'การนวดด้วยยาหรือน้ำมันหอมระเหยที่หลัง', 'T', 'N', '', 'Y', '1', null, null, null, '1', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('5907811', 'การนวดด้วยวิธีการแพทย์แผนไทยแบบราชสำนักที่หลัง', 'T', 'N', '', 'Y', '1', null, null, null, '1', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('5907812', 'การนวดด้วยวิธีการแพทย์แผนไทยแบบเชลยศักดิ์ที่หลัง', 'T', 'N', '', 'Y', '1', null, null, null, '1', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('5907818', 'การนวดด้วยวิธีการแพทย์แผนไทยแบบอื่นที่หลัง', 'T', 'N', '', 'Y', '1', null, null, null, '1', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('5907819', 'การนวดด้วยวิธีการแพทย์แผนไทย ไม่ระบุรายละเอียดที่หลัง', 'T', 'N', '', 'Y', '1', null, null, null, '1', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('5907820', 'การประคบด้วยสมุนไพรที่หลัง', 'T', 'N', '', 'Y', null, null, '1', null, '3', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('5907821', 'การประคบความร้อนที่หลัง', 'T', 'N', '', 'Y', null, null, '1', null, '3', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('5907822', 'การประคบความเย็นที่หลัง', 'T', 'N', '', 'Y', null, null, '1', null, '3', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('5907830', 'การทาหรือชโลมด้วยยาหรือน้ำมันหอมระเหยที่หลัง', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('5907838', 'การใช้ยาบำบัดวิธีอื่นที่หลัง', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('5907839', 'การใช้ยาบำบัด ไม่ระบุวิธีที่หลัง', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('5907880', 'การปฐมพยาบาลกระดูกหักที่หลัง', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('5907888', 'หัตถการอื่น ระบุวิธีที่หลัง', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('5907889', 'หัตถการอื่น ไม่ระบุวิธีที่หลัง', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('7217700', 'การบริบาลหญิงตั้งครรภ์ด้วยการนวดที่ไหล่ บ่า', 'T', 'N', '', 'Y', '1', null, null, null, '1', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('7217701', 'การบริบาลหญิงตั้งครรภ์ด้วยการประคบที่ไหล่ บ่า', 'T', 'N', '', 'Y', null, null, '1', null, '3', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('7217708', 'การบริบาลหญิงตั้งครรภ์ด้วยวิธีอื่นที่ไหล่ บ่า', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('7217709', 'การบริบาลหญิงตั้งครรภ์ ไม่ระบุวิธีที่ไหล่ บ่า', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('7217710', 'การบริบาลหญิงหลังคลอดด้วยการใช้ยาสมุนไพรที่ไหล่ บ่า', 'T', 'N', '', 'Y', null, null, null, '1', '4', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('7217713', 'การบริบาลหญิงหลังคลอดด้วยการนวดที่ไหล่ บ่า', 'T', 'N', '', 'Y', '1', null, null, '1', '1', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('7217714', 'การบริบาลหญิงหลังคลอดด้วยการประคบสมุนไพรที่ไหล่ บ่า', 'T', 'N', '', 'Y', null, null, '1', '1', '3', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('7217748', 'การบริบาลหญิงหลังคลอดด้วยวิธีอื่นที่ไหล่ บ่า', 'T', 'N', '', 'Y', null, null, null, '1', '4', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('7217749', 'การบริบาลหญิงหลังคลอด ไม่ระบุวิธีที่ไหล่ บ่า', 'T', 'N', '', 'Y', null, null, null, '1', '4', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('7217810', 'การนวดด้วยยาหรือน้ำมันหอมระเหยที่ไหล่ บ่า', 'T', 'N', '', 'Y', '1', null, null, null, '1', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('7217811', 'การนวดด้วยวิธีการแพทย์แผนไทยแบบราชสำนักที่ไหล่ บ่า', 'T', 'N', '', 'Y', '1', null, null, null, '1', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('7217812', 'การนวดด้วยวิธีการแพทย์แผนไทยแบบเชลยศักดิ์ที่ไหล่ บ่า', 'T', 'N', '', 'Y', '1', null, null, null, '1', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('7217818', 'การนวดด้วยวิธีการแพทย์แผนไทยแบบอื่นที่ไหล่ บ่า', 'T', 'N', '', 'Y', '1', null, null, null, '1', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('7217819', 'การนวดด้วยวิธีการแพทย์แผนไทย ไม่ระบุรายละเอียดที่ไหล่ บ่า', 'T', 'N', '', 'Y', '1', null, null, null, '1', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('7217820', 'การประคบด้วยสมุนไพรที่ไหล่ บ่า', 'T', 'N', '', 'Y', null, null, '1', null, '3', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('7217821', 'การประคบความร้อนที่ไหล่ บ่า', 'T', 'N', '', 'Y', null, null, '1', null, '3', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('7217822', 'การประคบความเย็นที่ไหล่ บ่า', 'T', 'N', '', 'Y', null, null, '1', null, '3', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('7217830', 'การทาหรือชโลมด้วยยาหรือน้ำมันหอมระเหยที่ไหล่ บ่า', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('7217838', 'การใช้ยาบำบัดวิธีอื่นที่ไหล่ บ่า', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('7217839', 'การใช้ยาบำบัด ไม่ระบุวิธีที่ไหล่ บ่า', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('7217880', 'การปฐมพยาบาลกระดูกหักที่ไหล่ บ่า', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('7217888', 'หัตถการอื่น ระบุวิธีที่ไหล่ บ่า', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('7217889', 'หัตถการอื่น ไม่ระบุวิธีที่ไหล่ บ่า', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('7227700', 'การบริบาลหญิงตั้งครรภ์ด้วยการนวดที่ต้นแขน', 'T', 'N', '', 'Y', '1', null, null, null, '1', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('7227701', 'การบริบาลหญิงตั้งครรภ์ด้วยการประคบที่ต้นแขน', 'T', 'N', '', 'Y', null, null, '1', null, '3', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('7227708', 'การบริบาลหญิงตั้งครรภ์ด้วยวิธีอื่นที่ต้นแขน', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('7227709', 'การบริบาลหญิงตั้งครรภ์ ไม่ระบุวิธีที่ต้นแขน', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('7227710', 'การบริบาลหญิงหลังคลอดด้วยการใช้ยาสมุนไพรที่ต้นแขน', 'T', 'N', '', 'Y', null, null, null, '1', '4', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('7227713', 'การบริบาลหญิงหลังคลอดด้วยการนวดที่ต้นแขน', 'T', 'N', '', 'Y', '1', null, null, '1', '1', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('7227714', 'การบริบาลหญิงหลังคลอดด้วยการประคบสมุนไพรที่ต้นแขน', 'T', 'N', '', 'Y', null, null, '1', '1', '3', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('7227748', 'การบริบาลหญิงหลังคลอดด้วยวิธีอื่นที่ต้นแขน', 'T', 'N', '', 'Y', null, null, null, '1', '4', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('7227749', 'การบริบาลหญิงหลังคลอด ไม่ระบุวิธีที่ต้นแขน', 'T', 'N', '', 'Y', null, null, null, '1', '4', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('7227810', 'การนวดด้วยยาหรือน้ำมันหอมระเหยที่ต้นแขน', 'T', 'N', '', 'Y', '1', null, null, null, '1', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('7227811', 'การนวดด้วยวิธีการแพทย์แผนไทยแบบราชสำนักที่ต้นแขน', 'T', 'N', '', 'Y', '1', null, null, null, '1', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('7227812', 'การนวดด้วยวิธีการแพทย์แผนไทยแบบเชลยศักดิ์ที่ต้นแขน', 'T', 'N', '', 'Y', '1', null, null, null, '1', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('7227818', 'การนวดด้วยวิธีการแพทย์แผนไทยแบบอื่นที่ต้นแขน', 'T', 'N', '', 'Y', '1', null, null, null, '1', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('7227819', 'การนวดด้วยวิธีการแพทย์แผนไทย ไม่ระบุรายละเอียดที่ต้นแขน', 'T', 'N', '', 'Y', '1', null, null, null, '1', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('7227820', 'การประคบด้วยสมุนไพรที่ต้นแขน', 'T', 'N', '', 'Y', null, null, '1', null, '3', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('7227821', 'การประคบความร้อนที่ต้นแขน', 'T', 'N', '', 'Y', null, null, '1', null, '3', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('7227822', 'การประคบความเย็นที่ต้นแขน', 'T', 'N', '', 'Y', null, null, '1', null, '3', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('7227830', 'การทาหรือชโลมด้วยยาหรือน้ำมันหอมระเหยที่ต้นแขน', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('7227838', 'การใช้ยาบำบัดวิธีอื่นที่ต้นแขน', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('7227839', 'การใช้ยาบำบัด ไม่ระบุวิธีที่ต้นแขน', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('7227880', 'การปฐมพยาบาลกระดูกหักที่ต้นแขน', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('7227888', 'หัตถการอื่น ระบุวิธีที่ต้นแขน', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('7227889', 'หัตถการอื่น ไม่ระบุวิธีที่ต้นแขน', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('7247700', 'การบริบาลหญิงตั้งครรภ์ด้วยการนวดที่แขน', 'T', 'N', '', 'Y', '1', null, null, null, '1', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('7247701', 'การบริบาลหญิงตั้งครรภ์ด้วยการประคบที่แขน', 'T', 'N', '', 'Y', null, null, '1', null, '3', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('7247708', 'การบริบาลหญิงตั้งครรภ์ด้วยวิธีอื่นที่แขน', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('7247709', 'การบริบาลหญิงตั้งครรภ์ ไม่ระบุวิธีที่แขน', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('7247710', 'การบริบาลหญิงหลังคลอดด้วยการใช้ยาสมุนไพรที่แขน', 'T', 'N', '', 'Y', null, null, null, '1', '4', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('7247713', 'การบริบาลหญิงหลังคลอดด้วยการนวดที่แขน', 'T', 'N', '', 'Y', '1', null, null, '1', '1', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('7247714', 'การบริบาลหญิงหลังคลอดด้วยการประคบสมุนไพรที่แขน', 'T', 'N', '', 'Y', null, null, '1', '1', '3', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('7247748', 'การบริบาลหญิงหลังคลอดด้วยวิธีอื่นที่แขน', 'T', 'N', '', 'Y', null, null, null, '1', '4', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('7247749', 'การบริบาลหญิงหลังคลอด ไม่ระบุวิธีที่แขน', 'T', 'N', '', 'Y', null, null, null, '1', '4', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('7247763', 'การบริบาลทารกด้วยการดัดแขนขาให้เหมาะสมที่แขน', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('7247768', 'การบริบาลทารกด้วยวิธีอื่นที่แขน', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('7247769', 'การบริบาลทารก ไม่ระบุวิธีที่แขน', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('7247810', 'การนวดด้วยยาหรือน้ำมันหอมระเหยที่แขน', 'T', 'N', '', 'Y', '1', null, null, null, '1', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('7247811', 'การนวดด้วยวิธีการแพทย์แผนไทยแบบราชสำนักที่แขน', 'T', 'N', '', 'Y', '1', null, null, null, '1', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('7247812', 'การนวดด้วยวิธีการแพทย์แผนไทยแบบเชลยศักดิ์ที่แขน', 'T', 'N', '', 'Y', '1', null, null, null, '1', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('7247818', 'การนวดด้วยวิธีการแพทย์แผนไทยแบบอื่นที่แขน', 'T', 'N', '', 'Y', '1', null, null, null, '1', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('7247819', 'การนวดด้วยวิธีการแพทย์แผนไทย ไม่ระบุรายละเอียดที่แขน', 'T', 'N', '', 'Y', '1', null, null, null, '1', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('7247820', 'การประคบด้วยสมุนไพรที่แขน', 'T', 'N', '', 'Y', null, null, '1', null, '3', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('7247821', 'การประคบความร้อนที่แขน', 'T', 'N', '', 'Y', null, null, '1', null, '3', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('7247822', 'การประคบความเย็นที่แขน', 'T', 'N', '', 'Y', null, null, '1', null, '3', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('7247830', 'การทาหรือชโลมด้วยยาหรือน้ำมันหอมระเหยที่แขน', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('7247838', 'การใช้ยาบำบัดวิธีอื่นที่แขน', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('7247839', 'การใช้ยาบำบัด ไม่ระบุวิธีที่แขน', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('7247880', 'การปฐมพยาบาลกระดูกหักที่แขน', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('7247888', 'หัตถการอื่น ระบุวิธีที่แขน', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('7247889', 'หัตถการอื่น ไม่ระบุวิธีที่แขน', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('7257700', 'การบริบาลหญิงตั้งครรภ์ด้วยการนวดที่ข้อมือ', 'T', 'N', '', 'Y', '1', null, null, null, '1', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('7257701', 'การบริบาลหญิงตั้งครรภ์ด้วยการประคบที่ข้อมือ', 'T', 'N', '', 'Y', null, null, '1', null, '3', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('7257708', 'การบริบาลหญิงตั้งครรภ์ด้วยวิธีอื่นที่ข้อมือ', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('7257709', 'การบริบาลหญิงตั้งครรภ์ ไม่ระบุวิธีที่ข้อมือ', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('7257710', 'การบริบาลหญิงหลังคลอดด้วยการใช้ยาสมุนไพรที่ข้อมือ', 'T', 'N', '', 'Y', null, null, null, '1', '4', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('7257713', 'การบริบาลหญิงหลังคลอดด้วยการนวดที่ข้อมือ', 'T', 'N', '', 'Y', '1', null, null, '1', '1', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('7257714', 'การบริบาลหญิงหลังคลอดด้วยการประคบสมุนไพรที่ข้อมือ', 'T', 'N', '', 'Y', null, null, '1', '1', '3', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('7257748', 'การบริบาลหญิงหลังคลอดด้วยวิธีอื่นที่ข้อมือ', 'T', 'N', '', 'Y', null, null, null, '1', '4', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('7257749', 'การบริบาลหญิงหลังคลอด ไม่ระบุวิธีที่ข้อมือ', 'T', 'N', '', 'Y', null, null, null, '1', '4', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('7257810', 'การนวดด้วยยาหรือน้ำมันหอมระเหยที่ข้อมือ', 'T', 'N', '', 'Y', '1', null, null, null, '1', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('7257811', 'การนวดด้วยวิธีการแพทย์แผนไทยแบบราชสำนักที่ข้อมือ', 'T', 'N', '', 'Y', '1', null, null, null, '1', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('7257812', 'การนวดด้วยวิธีการแพทย์แผนไทยแบบเชลยศักดิ์ที่ข้อมือ', 'T', 'N', '', 'Y', '1', null, null, null, '1', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('7257818', 'การนวดด้วยวิธีการแพทย์แผนไทยแบบอื่นที่ข้อมือ', 'T', 'N', '', 'Y', '1', null, null, null, '1', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('7257819', 'การนวดด้วยวิธีการแพทย์แผนไทย ไม่ระบุรายละเอียดที่ข้อมือ', 'T', 'N', '', 'Y', '1', null, null, null, '1', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('7257820', 'การประคบด้วยสมุนไพรที่ข้อมือ', 'T', 'N', '', 'Y', null, null, '1', null, '3', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('7257821', 'การประคบความร้อนที่ข้อมือ', 'T', 'N', '', 'Y', null, null, '1', null, '3', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('7257822', 'การประคบความเย็นที่ข้อมือ', 'T', 'N', '', 'Y', null, null, '1', null, '3', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('7257830', 'การทาหรือชโลมด้วยยาหรือน้ำมันหอมระเหยที่ข้อมือ', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('7257838', 'การใช้ยาบำบัดวิธีอื่นที่ข้อมือ', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('7257839', 'การใช้ยาบำบัด ไม่ระบุวิธีที่ข้อมือ', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('7257880', 'การปฐมพยาบาลกระดูกหักที่ข้อมือ', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('7257888', 'หัตถการอื่น ระบุวิธีที่ข้อมือ', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('7257889', 'หัตถการอื่น ไม่ระบุวิธีที่ข้อมือ', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('7267700', 'การบริบาลหญิงตั้งครรภ์ด้วยการนวดที่มือ', 'T', 'N', '', 'Y', '1', null, null, null, '1', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('7267701', 'การบริบาลหญิงตั้งครรภ์ด้วยการประคบที่มือ', 'T', 'N', '', 'Y', null, null, '1', null, '3', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('7267708', 'การบริบาลหญิงตั้งครรภ์ด้วยวิธีอื่นที่มือ', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('7267709', 'การบริบาลหญิงตั้งครรภ์ ไม่ระบุวิธีที่มือ', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('7267710', 'การบริบาลหญิงหลังคลอดด้วยการใช้ยาสมุนไพรที่มือ', 'T', 'N', '', 'Y', null, null, null, '1', '4', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('7267713', 'การบริบาลหญิงหลังคลอดด้วยการนวดที่มือ', 'T', 'N', '', 'Y', '1', null, null, '1', '1', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('7267714', 'การบริบาลหญิงหลังคลอดด้วยการประคบสมุนไพรที่มือ', 'T', 'N', '', 'Y', null, null, '1', '1', '3', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('7267748', 'การบริบาลหญิงหลังคลอดด้วยวิธีอื่นที่มือ', 'T', 'N', '', 'Y', null, null, null, '1', '4', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('7267749', 'การบริบาลหญิงหลังคลอด ไม่ระบุวิธีที่มือ', 'T', 'N', '', 'Y', null, null, null, '1', '4', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('7267810', 'การนวดด้วยยาหรือน้ำมันหอมระเหยที่มือ', 'T', 'N', '', 'Y', '1', null, null, null, '1', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('7267811', 'การนวดด้วยวิธีการแพทย์แผนไทยแบบราชสำนักที่มือ', 'T', 'N', '', 'Y', '1', null, null, null, '1', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('7267812', 'การนวดด้วยวิธีการแพทย์แผนไทยแบบเชลยศักดิ์ที่มือ', 'T', 'N', '', 'Y', '1', null, null, null, '1', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('7267818', 'การนวดด้วยวิธีการแพทย์แผนไทยแบบอื่นที่มือ', 'T', 'N', '', 'Y', '1', null, null, null, '1', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('7267819', 'การนวดด้วยวิธีการแพทย์แผนไทย ไม่ระบุรายละเอียดที่มือ', 'T', 'N', '', 'Y', '1', null, null, null, '1', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('7267820', 'การประคบด้วยสมุนไพรที่มือ', 'T', 'N', '', 'Y', null, null, '1', null, '3', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('7267821', 'การประคบความร้อนที่มือ', 'T', 'N', '', 'Y', null, null, '1', null, '3', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('7267822', 'การประคบความเย็นที่มือ', 'T', 'N', '', 'Y', null, null, '1', null, '3', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('7267830', 'การทาหรือชโลมด้วยยาหรือน้ำมันหอมระเหยที่มือ', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('7267838', 'การใช้ยาบำบัดวิธีอื่นที่มือ', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('7267839', 'การใช้ยาบำบัด ไม่ระบุวิธีที่มือ', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('7267880', 'การปฐมพยาบาลกระดูกหักที่มือ', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('7267888', 'หัตถการอื่น ระบุวิธีที่มือ', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('7267889', 'หัตถการอื่น ไม่ระบุวิธีที่มือ', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('8717700', 'การบริบาลหญิงตั้งครรภ์ด้วยการนวดที่สะโพก เอว', 'T', 'N', '', 'Y', '1', null, null, null, '1', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('8717701', 'การบริบาลหญิงตั้งครรภ์ด้วยการประคบที่สะโพก เอว', 'T', 'N', '', 'Y', null, null, '1', null, '3', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('8717708', 'การบริบาลหญิงตั้งครรภ์ด้วยวิธีอื่นที่สะโพก เอว', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('8717709', 'การบริบาลหญิงตั้งครรภ์ ไม่ระบุวิธีที่สะโพก เอว', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('8717710', 'การบริบาลหญิงหลังคลอดด้วยการใช้ยาสมุนไพรที่สะโพก เอว', 'T', 'N', '', 'Y', null, null, null, '1', '4', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('8717713', 'การบริบาลหญิงหลังคลอดด้วยการนวดที่สะโพก เอว', 'T', 'N', '', 'Y', '1', null, null, '1', '1', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('8717714', 'การบริบาลหญิงหลังคลอดด้วยการประคบสมุนไพรที่สะโพก เอว', 'T', 'N', '', 'Y', null, null, '1', '1', '3', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('8717748', 'การบริบาลหญิงหลังคลอดด้วยวิธีอื่นที่สะโพก เอว', 'T', 'N', '', 'Y', null, null, null, '1', '4', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('8717749', 'การบริบาลหญิงหลังคลอด ไม่ระบุวิธีที่สะโพก เอว', 'T', 'N', '', 'Y', null, null, null, '1', '4', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('8717810', 'การนวดด้วยยาหรือน้ำมันหอมระเหยที่สะโพก เอว', 'T', 'N', '', 'Y', '1', null, null, null, '1', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('8717811', 'การนวดด้วยวิธีการแพทย์แผนไทยแบบราชสำนักที่สะโพก เอว', 'T', 'N', '', 'Y', '1', null, null, null, '1', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('8717812', 'การนวดด้วยวิธีการแพทย์แผนไทยแบบเชลยศักดิ์ที่สะโพก เอว', 'T', 'N', '', 'Y', '1', null, null, null, '1', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('8717818', 'การนวดด้วยวิธีการแพทย์แผนไทยแบบอื่นที่สะโพก เอว', 'T', 'N', '', 'Y', '1', null, null, null, '1', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('8717819', 'การนวดด้วยวิธีการแพทย์แผนไทย ไม่ระบุรายละเอียดที่สะโพก เอว', 'T', 'N', '', 'Y', '1', null, null, null, '1', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('8717820', 'การประคบด้วยสมุนไพรที่สะโพก เอว', 'T', 'N', '', 'Y', null, null, '1', null, '3', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('8717821', 'การประคบความร้อนที่สะโพก เอว', 'T', 'N', '', 'Y', null, null, '1', null, '3', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('8717822', 'การประคบความเย็นที่สะโพก เอว', 'T', 'N', '', 'Y', null, null, '1', null, '3', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('8717830', 'การทาหรือชโลมด้วยยาหรือน้ำมันหอมระเหยที่สะโพก เอว', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('8717838', 'การใช้ยาบำบัดวิธีอื่นที่สะโพก เอว', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('8717839', 'การใช้ยาบำบัด ไม่ระบุวิธีที่สะโพก เอว', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('8717880', 'การปฐมพยาบาลกระดูกหักที่สะโพก เอว', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('8717888', 'หัตถการอื่น ระบุวิธีที่สะโพก เอว', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('8717889', 'หัตถการอื่น ไม่ระบุวิธีที่สะโพก เอว', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('8727700', 'การบริบาลหญิงตั้งครรภ์ด้วยการนวดที่ต้นขา', 'T', 'N', '', 'Y', '1', null, null, null, '1', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('8727701', 'การบริบาลหญิงตั้งครรภ์ด้วยการประคบที่ต้นขา', 'T', 'N', '', 'Y', null, null, '1', null, '3', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('8727708', 'การบริบาลหญิงตั้งครรภ์ด้วยวิธีอื่นที่ต้นขา', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('8727709', 'การบริบาลหญิงตั้งครรภ์ ไม่ระบุวิธีที่ต้นขา', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('8727710', 'การบริบาลหญิงหลังคลอดด้วยการใช้ยาสมุนไพรที่ต้นขา', 'T', 'N', '', 'Y', null, null, null, '1', '4', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('8727713', 'การบริบาลหญิงหลังคลอดด้วยการนวดที่ต้นขา', 'T', 'N', '', 'Y', '1', null, null, '1', '1', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('8727714', 'การบริบาลหญิงหลังคลอดด้วยการประคบสมุนไพรที่ต้นขา', 'T', 'N', '', 'Y', null, null, '1', '1', '3', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('8727748', 'การบริบาลหญิงหลังคลอดด้วยวิธีอื่นที่ต้นขา', 'T', 'N', '', 'Y', null, null, null, '1', '4', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('8727749', 'การบริบาลหญิงหลังคลอด ไม่ระบุวิธีที่ต้นขา', 'T', 'N', '', 'Y', null, null, null, '1', '4', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('8727810', 'การนวดด้วยยาหรือน้ำมันหอมระเหยที่ต้นขา', 'T', 'N', '', 'Y', '1', null, null, null, '1', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('8727811', 'การนวดด้วยวิธีการแพทย์แผนไทยแบบราชสำนักที่ต้นขา', 'T', 'N', '', 'Y', '1', null, null, null, '1', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('8727812', 'การนวดด้วยวิธีการแพทย์แผนไทยแบบเชลยศักดิ์ที่ต้นขา', 'T', 'N', '', 'Y', '1', null, null, null, '1', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('8727818', 'การนวดด้วยวิธีการแพทย์แผนไทยแบบอื่นที่ต้นขา', 'T', 'N', '', 'Y', '1', null, null, null, '1', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('8727819', 'การนวดด้วยวิธีการแพทย์แผนไทย ไม่ระบุรายละเอียดที่ต้นขา', 'T', 'N', '', 'Y', '1', null, null, null, '1', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('8727820', 'การประคบด้วยสมุนไพรที่ต้นขา', 'T', 'N', '', 'Y', null, null, '1', null, '3', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('8727821', 'การประคบความร้อนที่ต้นขา', 'T', 'N', '', 'Y', null, null, '1', null, '3', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('8727822', 'การประคบความเย็นที่ต้นขา', 'T', 'N', '', 'Y', null, null, '1', null, '3', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('8727830', 'การทาหรือชโลมด้วยยาหรือน้ำมันหอมระเหยที่ต้นขา', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('8727838', 'การใช้ยาบำบัดวิธีอื่นที่ต้นขา', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('8727839', 'การใช้ยาบำบัด ไม่ระบุวิธีที่ต้นขา', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('8727880', 'การปฐมพยาบาลกระดูกหักที่ต้นขา', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('8727888', 'หัตถการอื่น ระบุวิธีที่ต้นขา', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('8727889', 'หัตถการอื่น ไม่ระบุวิธีที่ต้นขา', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('8737700', 'การบริบาลหญิงตั้งครรภ์ด้วยการนวดที่หัวเข่า', 'T', 'N', '', 'Y', '1', null, null, null, '1', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('8737701', 'การบริบาลหญิงตั้งครรภ์ด้วยการประคบที่หัวเข่า', 'T', 'N', '', 'Y', null, null, '1', null, '3', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('8737708', 'การบริบาลหญิงตั้งครรภ์ด้วยวิธีอื่นที่หัวเข่า', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('8737709', 'การบริบาลหญิงตั้งครรภ์ ไม่ระบุวิธีที่หัวเข่า', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('8737710', 'การบริบาลหญิงหลังคลอดด้วยการใช้ยาสมุนไพรที่หัวเข่า', 'T', 'N', '', 'Y', null, null, null, '1', '4', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('8737713', 'การบริบาลหญิงหลังคลอดด้วยการนวดที่หัวเข่า', 'T', 'N', '', 'Y', '1', null, null, '1', '1', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('8737714', 'การบริบาลหญิงหลังคลอดด้วยการประคบสมุนไพรที่หัวเข่า', 'T', 'N', '', 'Y', null, null, '1', '1', '3', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('8737748', 'การบริบาลหญิงหลังคลอดด้วยวิธีอื่นที่หัวเข่า', 'T', 'N', '', 'Y', null, null, null, '1', '4', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('8737749', 'การบริบาลหญิงหลังคลอด ไม่ระบุวิธีที่หัวเข่า', 'T', 'N', '', 'Y', null, null, null, '1', '4', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('8737810', 'การนวดด้วยยาหรือน้ำมันหอมระเหยที่หัวเข่า', 'T', 'N', '', 'Y', '1', null, null, null, '1', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('8737811', 'การนวดด้วยวิธีการแพทย์แผนไทยแบบราชสำนักที่หัวเข่า', 'T', 'N', '', 'Y', '1', null, null, null, '1', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('8737812', 'การนวดด้วยวิธีการแพทย์แผนไทยแบบเชลยศักดิ์ที่หัวเข่า', 'T', 'N', '', 'Y', '1', null, null, null, '1', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('8737818', 'การนวดด้วยวิธีการแพทย์แผนไทยแบบอื่นที่หัวเข่า', 'T', 'N', '', 'Y', '1', null, null, null, '1', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('8737819', 'การนวดด้วยวิธีการแพทย์แผนไทย ไม่ระบุรายละเอียดที่หัวเข่า', 'T', 'N', '', 'Y', '1', null, null, null, '1', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('8737820', 'การประคบด้วยสมุนไพรที่หัวเข่า', 'T', 'N', '', 'Y', null, null, '1', null, '3', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('8737821', 'การประคบความร้อนที่หัวเข่า', 'T', 'N', '', 'Y', null, null, '1', null, '3', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('8737822', 'การประคบความเย็นที่หัวเข่า', 'T', 'N', '', 'Y', null, null, '1', null, '3', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('8737830', 'การทาหรือชโลมด้วยยาหรือน้ำมันหอมระเหยที่หัวเข่า', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('8737838', 'การใช้ยาบำบัดวิธีอื่นที่หัวเข่า', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('8737839', 'การใช้ยาบำบัด ไม่ระบุวิธีที่หัวเข่า', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('8737880', 'การปฐมพยาบาลกระดูกหักที่หัวเข่า', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('8737888', 'หัตถการอื่น ระบุวิธีที่หัวเข่า', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('8737889', 'หัตถการอื่น ไม่ระบุวิธีที่หัวเข่า', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('8747700', 'การบริบาลหญิงตั้งครรภ์ด้วยการนวดที่ขา', 'T', 'N', '', 'Y', '1', null, null, null, '1', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('8747701', 'การบริบาลหญิงตั้งครรภ์ด้วยการประคบที่ขา', 'T', 'N', '', 'Y', null, null, '1', null, '3', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('8747708', 'การบริบาลหญิงตั้งครรภ์ด้วยวิธีอื่นที่ขา', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('8747709', 'การบริบาลหญิงตั้งครรภ์ ไม่ระบุวิธีที่ขา', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('8747710', 'การบริบาลหญิงหลังคลอดด้วยการใช้ยาสมุนไพรที่ขา', 'T', 'N', '', 'Y', null, null, null, '1', '4', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('8747713', 'การบริบาลหญิงหลังคลอดด้วยการนวดที่ขา', 'T', 'N', '', 'Y', '1', null, null, '1', '1', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('8747714', 'การบริบาลหญิงหลังคลอดด้วยการประคบสมุนไพรที่ขา', 'T', 'N', '', 'Y', null, null, '1', '1', '3', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('8747748', 'การบริบาลหญิงหลังคลอดด้วยวิธีอื่นที่ขา', 'T', 'N', '', 'Y', null, null, null, '1', '4', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('8747749', 'การบริบาลหญิงหลังคลอด ไม่ระบุวิธีที่ขา', 'T', 'N', '', 'Y', null, null, null, '1', '4', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('8747763', 'การบริบาลทารกด้วยการดัดแขนขาให้เหมาะสมที่ขา', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('8747768', 'การบริบาลทารกด้วยวิธีอื่นที่ขา', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('8747769', 'การบริบาลทารก ไม่ระบุวิธีที่ขา', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('8747810', 'การนวดด้วยยาหรือน้ำมันหอมระเหยที่ขา', 'T', 'N', '', 'Y', '1', null, null, null, '1', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('8747811', 'การนวดด้วยวิธีการแพทย์แผนไทยแบบราชสำนักที่ขา', 'T', 'N', '', 'Y', '1', null, null, null, '1', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('8747812', 'การนวดด้วยวิธีการแพทย์แผนไทยแบบเชลยศักดิ์ที่ขา', 'T', 'N', '', 'Y', '1', null, null, null, '1', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('8747818', 'การนวดด้วยวิธีการแพทย์แผนไทยแบบอื่นที่ขา', 'T', 'N', '', 'Y', '1', null, null, null, '1', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('8747819', 'การนวดด้วยวิธีการแพทย์แผนไทย ไม่ระบุรายละเอียดที่ขา', 'T', 'N', '', 'Y', '1', null, null, null, '1', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('8747820', 'การประคบด้วยสมุนไพรที่ขา', 'T', 'N', '', 'Y', null, null, '1', null, '3', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('8747821', 'การประคบความร้อนที่ขา', 'T', 'N', '', 'Y', null, null, '1', null, '3', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('8747822', 'การประคบความเย็นที่ขา', 'T', 'N', '', 'Y', null, null, '1', null, '3', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('8747830', 'การทาหรือชโลมด้วยยาหรือน้ำมันหอมระเหยที่ขา', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('8747838', 'การใช้ยาบำบัดวิธีอื่นที่ขา', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('8747839', 'การใช้ยาบำบัด ไม่ระบุวิธีที่ขา', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('8747880', 'การปฐมพยาบาลกระดูกหักที่ขา', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('8747888', 'หัตถการอื่น ระบุวิธีที่ขา', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('8747889', 'หัตถการอื่น ไม่ระบุวิธีที่ขา', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('8757700', 'การบริบาลหญิงตั้งครรภ์ด้วยการนวดที่ข้อเท้า', 'T', 'N', '', 'Y', '1', null, null, null, '1', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('8757701', 'การบริบาลหญิงตั้งครรภ์ด้วยการประคบที่ข้อเท้า', 'T', 'N', '', 'Y', null, null, '1', null, '3', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('8757708', 'การบริบาลหญิงตั้งครรภ์ด้วยวิธีอื่นที่ข้อเท้า', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('8757709', 'การบริบาลหญิงตั้งครรภ์ ไม่ระบุวิธีที่ข้อเท้า', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('8757710', 'การบริบาลหญิงหลังคลอดด้วยการใช้ยาสมุนไพรที่ข้อเท้า', 'T', 'N', '', 'Y', null, null, null, '1', '4', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('8757713', 'การบริบาลหญิงหลังคลอดด้วยการนวดที่ข้อเท้า', 'T', 'N', '', 'Y', '1', null, null, '1', '1', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('8757714', 'การบริบาลหญิงหลังคลอดด้วยการประคบสมุนไพรที่ข้อเท้า', 'T', 'N', '', 'Y', null, null, '1', '1', '3', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('8757748', 'การบริบาลหญิงหลังคลอดด้วยวิธีอื่นที่ข้อเท้า', 'T', 'N', '', 'Y', null, null, null, '1', '4', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('8757749', 'การบริบาลหญิงหลังคลอด ไม่ระบุวิธีที่ข้อเท้า', 'T', 'N', '', 'Y', null, null, null, '1', '4', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('8757810', 'การนวดด้วยยาหรือน้ำมันหอมระเหยที่ข้อเท้า', 'T', 'N', '', 'Y', '1', null, null, null, '1', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('8757811', 'การนวดด้วยวิธีการแพทย์แผนไทยแบบราชสำนักที่ข้อเท้า', 'T', 'N', '', 'Y', '1', null, null, null, '1', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('8757812', 'การนวดด้วยวิธีการแพทย์แผนไทยแบบเชลยศักดิ์ที่ข้อเท้า', 'T', 'N', '', 'Y', '1', null, null, null, '1', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('8757818', 'การนวดด้วยวิธีการแพทย์แผนไทยแบบอื่นที่ข้อเท้า', 'T', 'N', '', 'Y', '1', null, null, null, '1', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('8757819', 'การนวดด้วยวิธีการแพทย์แผนไทย ไม่ระบุรายละเอียดที่ข้อเท้า', 'T', 'N', '', 'Y', '1', null, null, null, '1', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('8757820', 'การประคบด้วยสมุนไพรที่ข้อเท้า', 'T', 'N', '', 'Y', null, null, '1', null, '3', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('8757821', 'การประคบความร้อนที่ข้อเท้า', 'T', 'N', '', 'Y', null, null, '1', null, '3', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('8757822', 'การประคบความเย็นที่ข้อเท้า', 'T', 'N', '', 'Y', null, null, '1', null, '3', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('8757830', 'การทาหรือชโลมด้วยยาหรือน้ำมันหอมระเหยที่ข้อเท้า', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('8757838', 'การใช้ยาบำบัดวิธีอื่นที่ข้อเท้า', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('8757839', 'การใช้ยาบำบัด ไม่ระบุวิธีที่ข้อเท้า', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('8757880', 'การปฐมพยาบาลกระดูกหักที่ข้อเท้า', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('8757888', 'หัตถการอื่น ระบุวิธีที่ข้อเท้า', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('8757889', 'หัตถการอื่น ไม่ระบุวิธีที่ข้อเท้า', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('8767700', 'การบริบาลหญิงตั้งครรภ์ด้วยการนวดที่เท้า', 'T', 'N', '', 'Y', '1', null, null, null, '1', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('8767701', 'การบริบาลหญิงตั้งครรภ์ด้วยการประคบที่เท้า', 'T', 'N', '', 'Y', null, null, '1', null, '3', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('8767708', 'การบริบาลหญิงตั้งครรภ์ด้วยวิธีอื่นที่เท้า', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('8767709', 'การบริบาลหญิงตั้งครรภ์ ไม่ระบุวิธีที่เท้า', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('8767710', 'การบริบาลหญิงหลังคลอดด้วยการใช้ยาสมุนไพรที่เท้า', 'T', 'N', '', 'Y', null, null, null, '1', '4', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('8767713', 'การบริบาลหญิงหลังคลอดด้วยการนวดที่เท้า', 'T', 'N', '', 'Y', '1', null, null, '1', '1', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('8767714', 'การบริบาลหญิงหลังคลอดด้วยการประคบสมุนไพรที่เท้า', 'T', 'N', '', 'Y', null, null, '1', '1', '3', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('8767748', 'การบริบาลหญิงหลังคลอดด้วยวิธีอื่นที่เท้า', 'T', 'N', '', 'Y', null, null, null, '1', '4', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('8767749', 'การบริบาลหญิงหลังคลอด ไม่ระบุวิธีที่เท้า', 'T', 'N', '', 'Y', null, null, null, '1', '4', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('8767810', 'การนวดด้วยยาหรือน้ำมันหอมระเหยที่เท้า', 'T', 'N', '', 'Y', '1', null, null, null, '1', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('8767811', 'การนวดด้วยวิธีการแพทย์แผนไทยแบบราชสำนักที่เท้า', 'T', 'N', '', 'Y', '1', null, null, null, '1', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('8767812', 'การนวดด้วยวิธีการแพทย์แผนไทยแบบเชลยศักดิ์ที่เท้า', 'T', 'N', '', 'Y', '1', null, null, null, '1', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('8767818', 'การนวดด้วยวิธีการแพทย์แผนไทยแบบอื่นที่เท้า', 'T', 'N', '', 'Y', '1', null, null, null, '1', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('8767819', 'การนวดด้วยวิธีการแพทย์แผนไทย ไม่ระบุรายละเอียดที่เท้า', 'T', 'N', '', 'Y', '1', null, null, null, '1', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('8767820', 'การประคบด้วยสมุนไพรที่เท้า', 'T', 'N', '', 'Y', null, null, '1', null, '3', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('8767821', 'การประคบความร้อนที่เท้า', 'T', 'N', '', 'Y', null, null, '1', null, '3', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('8767822', 'การประคบความเย็นที่เท้า', 'T', 'N', '', 'Y', null, null, '1', null, '3', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('8767830', 'การทาหรือชโลมด้วยยาหรือน้ำมันหอมระเหยที่เท้า', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('8767838', 'การใช้ยาบำบัดวิธีอื่นที่เท้า', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('8767839', 'การใช้ยาบำบัด ไม่ระบุวิธีที่เท้า', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('8767880', 'การปฐมพยาบาลกระดูกหักที่เท้า', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('8767888', 'หัตถการอื่น ระบุวิธีที่เท้า', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('8767889', 'หัตถการอื่น ไม่ระบุวิธีที่เท้า', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('9007700', 'การบริบาลหญิงตั้งครรภ์ด้วยการนวดที่ทั่วร่างกาย', 'T', 'N', '', 'Y', '1', null, null, null, '1', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('9007701', 'การบริบาลหญิงตั้งครรภ์ด้วยการประคบที่ทั่วร่างกาย', 'T', 'N', '', 'Y', null, null, '1', null, '3', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('9007708', 'การบริบาลหญิงตั้งครรภ์ด้วยวิธีอื่นที่ทั่วร่างกาย', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('9007709', 'การบริบาลหญิงตั้งครรภ์ ไม่ระบุวิธีที่ทั่วร่างกาย', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('9007710', 'การบริบาลหญิงหลังคลอดด้วยการใช้ยาสมุนไพรที่ทั่วร่างกาย', 'T', 'N', '', 'Y', null, null, null, '1', '4', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('9007712', 'การบริบาลหญิงหลังคลอดด้วยการทับหม้อเกลือที่ทั่วร่างกาย', 'T', 'N', '', 'Y', null, null, null, '1', '4', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('9007713', 'การบริบาลหญิงหลังคลอดด้วยการนวดที่ทั่วร่างกาย', 'T', 'N', '', 'Y', '1', null, null, '1', '1', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('9007714', 'การบริบาลหญิงหลังคลอดด้วยการประคบสมุนไพรที่ทั่วร่างกาย', 'T', 'N', '', 'Y', null, null, '1', '1', '3', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('9007715', 'การบริบาลหญิงหลังคลอดด้วยการเข้ากระโจมที่ทั่วร่างกาย', 'T', 'N', '', 'Y', null, null, null, '1', '4', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('9007716', 'การบริบาลหญิงหลังคลอดด้วยการอบไอน้ำสมุนไพรที่ทั่วร่างกาย', 'T', 'N', '', 'Y', null, '1', null, '1', '2', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('9007720', 'การบริบาลหญิงหลังคลอดด้วยการอยู่ไฟที่ทั่วร่างกาย', 'T', 'N', '', 'Y', null, null, null, '1', '4', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('9007721', 'การบริบาลหญิงหลังคลอดด้วยการนาบอิฐ (ก้อนเส้า)ที่หน้าท้อง', 'T', 'N', '', 'Y', null, null, null, '1', '4', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('9007722', 'การบริบาลหญิงหลังคลอดด้วยการอาบสมุนไพรที่ทั่วร่างกาย', 'T', 'N', '', 'Y', null, null, null, '1', '4', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('9007730', 'การบริบาลหญิงหลังคลอดด้วยการปฏิบัติตัวสำหรับหลังคลอดที่ทั่วร่างกาย', 'T', 'N', '', 'Y', null, null, null, '1', '4', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('9007748', 'การบริบาลหญิงหลังคลอดด้วยวิธีอื่นที่ทั่วร่างกาย', 'T', 'N', '', 'Y', null, null, null, '1', '4', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('9007749', 'การบริบาลหญิงหลังคลอด ไม่ระบุวิธีที่ทั่วร่างกาย', 'T', 'N', '', 'Y', null, null, null, '1', '4', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('9007760', 'การบริบาลทารกด้วยการแต่งตัวที่ทั่วร่างกาย', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('9007764', 'การบริบารทารกด้วยการใช้ยาสมุนไพรที่ทั่วร่างกาย', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('9007768', 'การบริบาลทารกด้วยวิธีอื่นที่ทั่วร่างกาย', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('9007769', 'การบริบาลทารก ไม่ระบุวิธีที่ทั่วร่างกาย', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('9007800', 'การอบไอน้ำสมุนไพรที่ทั่วร่างกาย', 'T', 'N', '', 'Y', null, '1', null, null, '2', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('9007802', 'การเข้ากระโจมที่ทั่วร่างกาย', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('9007803', 'การอาบสมุนไพรที่ทั่วร่างกาย', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('9007808', 'การบำบัดทั่วร่างกายวิธีอื่นที่ทั่วร่างกาย', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('9007809', 'การบำบัดทั่วร่างกาย ไม่ระบุวิธีที่ทั่วร่างกาย', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('9007810', 'การนวดด้วยยาหรือน้ำมันหอมระเหยที่ทั่วร่างกาย', 'T', 'N', '', 'Y', '1', null, null, null, '1', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('9007811', 'การนวดด้วยวิธีการแพทย์แผนไทยแบบราชสำนักที่ทั่วร่างกาย', 'T', 'N', '', 'Y', '1', null, null, null, '1', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('9007812', 'การนวดด้วยวิธีการแพทย์แผนไทยแบบเชลยศักดิ์ที่ทั่วร่างกาย', 'T', 'N', '', 'Y', '1', null, null, null, '1', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('9007818', 'การนวดด้วยวิธีการแพทย์แผนไทยแบบอื่นที่ทั่วร่างกาย', 'T', 'N', '', 'Y', '1', null, null, null, '1', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('9007819', 'การนวดด้วยวิธีการแพทย์แผนไทย ไม่ระบุรายละเอียดที่ทั่วร่างกาย', 'T', 'N', '', 'Y', '1', null, null, null, '1', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('9007820', 'การประคบด้วยสมุนไพรที่ทั่วร่างกาย', 'T', 'N', '', 'Y', null, null, '1', null, '3', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('9007821', 'การประคบความร้อนที่ทั่วร่างกาย', 'T', 'N', '', 'Y', null, null, '1', null, '3', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('9007822', 'การประคบความเย็นที่ทั่วร่างกาย', 'T', 'N', '', 'Y', null, null, '1', null, '3', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('9007830', 'การทาหรือชโลมด้วยยาหรือน้ำมันหอมระเหยที่ทั่วร่างกาย', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('9007833', 'การสุมยาสมุนไพรที่ทั่วร่างกาย', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('9007838', 'การใช้ยาบำบัดวิธีอื่นที่ทั่วร่างกาย', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('9007839', 'การใช้ยาบำบัด ไม่ระบุวิธีที่ทั่วร่างกาย', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('9007880', 'การปฐมพยาบาลกระดูกหักที่ทั่วร่างกาย', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('9007888', 'หัตถการอื่น ระบุวิธีที่ทั่วร่างกาย', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('9007889', 'หัตถการอื่น ไม่ระบุวิธีที่ทั่วร่างกาย', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('9007900', 'การส่งเสริมสุขภาพและการป้องกันโรคด้วยการนวดตัวเพื่อสุขภาพ ที่ทั่วร่างกาย', 'T', 'N', '', 'Y', '1', null, null, null, '1', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('9007901', 'การส่งเสริมสุขภาพและการป้องกันโรคด้วยการอบไอน้ำสมุนไพรเพื่อสุขภาพ ที่ทั่วร่างกาย', 'T', 'N', '', 'Y', null, '1', null, null, '2', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('9007902', 'การส่งเสริมสุขภาพและการป้องกันโรคด้วยการบริหารร่างกายด้วยท่าฤๅษีดัดตน ที่ทั่วร่างกาย', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('9007903', 'การส่งเสริมสุขภาพและการป้องกันโรคด้วยการนั่งสมาธิ ที่ทั่วร่างกาย', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('9007904', 'การส่งเสริมสุขภาพและการป้องกันโรคด้วยการรับประทานอาหารสุขภาพที่ทั่วร่างกาย', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('9007998', 'การส่งเสริมสุขภาพและการป้องกันโรคด้วยวิธีอื่นที่ทั่วร่างกาย', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('9007999', 'การส่งเสริมสุขภาพและการป้องกันโรค ไม่ระบุวิธีที่ทั่วร่างกาย', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('9997700', 'การบริบาลหญิงตั้งครรภ์ด้วยการนวดที่ไม่ระบุตำแหน่ง', 'T', 'N', '', 'Y', '1', null, null, null, '1', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('9997701', 'การบริบาลหญิงตั้งครรภ์ด้วยการประคบที่ไม่ระบุตำแหน่ง', 'T', 'N', '', 'Y', null, null, '1', null, '3', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('9997708', 'การบริบาลหญิงตั้งครรภ์ด้วยวิธีอื่นที่ไม่ระบุตำแหน่ง', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('9997709', 'การบริบาลหญิงตั้งครรภ์ ไม่ระบุวิธีที่ไม่ระบุตำแหน่ง', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('9997710', 'การบริบาลหญิงหลังคลอดด้วยการใช้ยาสมุนไพรที่ไม่ระบุตำแหน่ง', 'T', 'N', '', 'Y', null, null, null, '1', '4', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('9997713', 'การบริบาลหญิงหลังคลอดด้วยการนวดที่ไม่ระบุตำแหน่ง', 'T', 'N', '', 'Y', '1', null, null, '1', '1', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('9997714', 'การบริบาลหญิงหลังคลอดด้วยการประคบสมุนไพรที่ไม่ระบุตำแหน่ง', 'T', 'N', '', 'Y', null, null, '1', '1', '3', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('9997748', 'การบริบาลหญิงหลังคลอดด้วยวิธีอื่นที่ไม่ระบุตำแหน่ง', 'T', 'N', '', 'Y', null, null, null, '1', '4', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('9997749', 'การบริบาลหญิงหลังคลอด ไม่ระบุวิธีที่ไม่ระบุตำแหน่ง', 'T', 'N', '', 'Y', null, null, null, '1', '4', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('9997764', 'การบริบารทารกด้วยการใช้ยาสมุนไพรที่ไม่ระบุตำแหน่ง', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('9997768', 'การบริบาลทารกด้วยวิธีอื่นที่ไม่ระบุตำแหน่ง', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('9997769', 'การบริบาลทารก ไม่ระบุวิธีที่ไม่ระบุตำแหน่ง', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('9997810', 'การนวดด้วยยาหรือน้ำมันหอมระเหยที่ไม่ระบุตำแหน่ง', 'T', 'N', '', 'Y', '1', null, null, null, '1', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('9997811', 'การนวดด้วยวิธีการแพทย์แผนไทยแบบราชสำนักที่ไม่ระบุตำแหน่ง', 'T', 'N', '', 'Y', '1', null, null, null, '1', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('9997812', 'การนวดด้วยวิธีการแพทย์แผนไทยแบบเชลยศักดิ์ที่ไม่ระบุตำแหน่ง', 'T', 'N', '', 'Y', '1', null, null, null, '1', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('9997818', 'การนวดด้วยวิธีการแพทย์แผนไทยแบบอื่นที่ไม่ระบุตำแหน่ง', 'T', 'N', '', 'Y', '1', null, null, null, '1', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('9997819', 'การนวดด้วยวิธีการแพทย์แผนไทย ไม่ระบุรายละเอียดที่ไม่ระบุตำแหน่ง', 'T', 'N', '', 'Y', '1', null, null, null, '1', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('9997820', 'การประคบด้วยสมุนไพรที่ไม่ระบุตำแหน่ง', 'T', 'N', '', 'Y', null, null, '1', null, '3', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('9997821', 'การประคบความร้อนที่ไม่ระบุตำแหน่ง', 'T', 'N', '', 'Y', null, null, '1', null, '3', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('9997822', 'การประคบความเย็นที่ไม่ระบุตำแหน่ง', 'T', 'N', '', 'Y', null, null, '1', null, '3', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('9997830', 'การทาหรือชโลมด้วยยาหรือน้ำมันหอมระเหยที่ไม่ระบุตำแหน่ง', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('9997838', 'การใช้ยาบำบัดวิธีอื่นที่ไม่ระบุตำแหน่ง', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('9997839', 'การใช้ยาบำบัด ไม่ระบุวิธีที่ไม่ระบุตำแหน่ง', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('9997880', 'การปฐมพยาบาลกระดูกหักที่ไม่ระบุตำแหน่ง', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('9997888', 'หัตถการอื่น ระบุวิธีที่ไม่ระบุตำแหน่ง', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
INSERT INTO `cicd9ttm_planthai` VALUES ('9997889', 'หัตถการอื่น ไม่ระบุวิธีที่ไม่ระบุตำแหน่ง', 'T', 'N', '', 'Y', null, null, null, null, '0', null);
