/*
Navicat MySQL Data Transfer

Source Server         : local-mariadb
Source Server Version : 50540
Source Host           : localhost:3309
Source Database       : dhdc_ctable

Target Server Type    : MYSQL
Target Server Version : 50540
File Encoding         : 65001

Date: 2015-04-07 20:41:52
*/

SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for cprename
-- ----------------------------
DROP TABLE IF EXISTS `cprename`;
CREATE TABLE `cprename` (
  `id_prename` varchar(3) NOT NULL,
  `prename` varchar(50) NOT NULL,
  `detail` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`id_prename`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records of cprename
-- ----------------------------
INSERT INTO `cprename` VALUES ('001', 'ด.ช.', 'เด็กชาย');
INSERT INTO `cprename` VALUES ('002', 'ด.ญ.', 'เด็กหญิง');
INSERT INTO `cprename` VALUES ('003', 'นาย', 'นาย');
INSERT INTO `cprename` VALUES ('004', 'น.ส.', 'นางสาว');
INSERT INTO `cprename` VALUES ('005', 'นาง', 'นาง');
INSERT INTO `cprename` VALUES ('006', 'น.ช.ม.ล.', 'นักโทษชายหม่อมหลวง');
INSERT INTO `cprename` VALUES ('007', 'น.ช.', 'นักโทษชาย');
INSERT INTO `cprename` VALUES ('008', 'น.ญ.', 'นักโทษหญิง');
INSERT INTO `cprename` VALUES ('009', 'น.ช.จ.ส.อ.', 'นักโทษชายจ่าสิบเอก');
INSERT INTO `cprename` VALUES ('010', 'น.ช.จ.อ.', 'นักโทษชายจ่าเอก');
INSERT INTO `cprename` VALUES ('011', 'น.ช.พลฯ.', 'นักโทษชายพลทหาร');
INSERT INTO `cprename` VALUES ('012', 'น.ช.ร.ต.', 'นักโทษชายร้อยตรี');
INSERT INTO `cprename` VALUES ('099', 'พระเจ้าหลานเธอ พระองค์เจ้า', 'พระเจ้าหลานเธอ พระองค์เจ้า');
INSERT INTO `cprename` VALUES ('100', 'พระบาทสมเด็จพระเจ้าอยู่หัว', 'พระบาทสมเด็จพระเจ้าอยู่หัว');
INSERT INTO `cprename` VALUES ('101', 'สมเด็จพระนางเจ้า', 'สมเด็จพระนางเจ้า');
INSERT INTO `cprename` VALUES ('102', 'สมเด็จพระศรีนครินทราบรมราชชนนี', 'สมเด็จพระศรีนครินทราบรมราชชนนี');
INSERT INTO `cprename` VALUES ('103', 'พลโทสมเด็จพระบรมโอรสาธิราช', 'พลโทสมเด็จพระบรมโอรสาธิราช');
INSERT INTO `cprename` VALUES ('104', 'พลตรีสมเด็จพระเทพรัตนราชสุดา', 'พลตรีสมเด็จพระเทพรัตนราชสุดา');
INSERT INTO `cprename` VALUES ('105', 'พระเจ้าวรวงศ์เธอพระองค์หญิง', 'พระเจ้าวรวงศ์เธอพระองค์หญิง');
INSERT INTO `cprename` VALUES ('106', 'พระเจ้าวรวงศ์เธอ พระองค์เจ้า', 'พระเจ้าวรวงศ์เธอ พระองค์เจ้า');
INSERT INTO `cprename` VALUES ('107', 'สมเด็จพระราชชนนี', 'สมเด็จพระราชชนนี');
INSERT INTO `cprename` VALUES ('108', 'สมเด็จพระเจ้าพี่นางเธอเจ้าฟ้า', 'สมเด็จพระเจ้าพี่นางเธอเจ้าฟ้า');
INSERT INTO `cprename` VALUES ('109', 'สมเด็จพระ', 'สมเด็จพระ');
INSERT INTO `cprename` VALUES ('110', 'สมเด็จพระเจ้าลูกเธอ', 'สมเด็จพระเจ้าลูกเธอ');
INSERT INTO `cprename` VALUES ('111', 'สมเด็จพระเจ้าลูกยาเธอ', 'สมเด็จพระเจ้าลูกยาเธอ');
INSERT INTO `cprename` VALUES ('112', 'สมเด็จเจ้าฟ้า', 'สมเด็จเจ้าฟ้า');
INSERT INTO `cprename` VALUES ('113', 'พระเจ้าบรมวงศ์เธอ', 'พระเจ้าบรมวงศ์เธอ');
INSERT INTO `cprename` VALUES ('114', 'พระเจ้าวรวงศ์เธอ', 'พระเจ้าวรวงศ์เธอ');
INSERT INTO `cprename` VALUES ('115', 'พระเจ้าหลานเธอ', 'พระเจ้าหลานเธอ');
INSERT INTO `cprename` VALUES ('116', 'พระเจ้าหลานยาเธอ', 'พระเจ้าหลานยาเธอ');
INSERT INTO `cprename` VALUES ('117', 'พระวรวงศ์เธอ', 'พระวรวงศ์เธอ');
INSERT INTO `cprename` VALUES ('118', 'สมเด็จพระเจ้าภคินีเธอ', 'สมเด็จพระเจ้าภคินีเธอ');
INSERT INTO `cprename` VALUES ('119', 'พระองค์เจ้า', 'พระองค์เจ้า');
INSERT INTO `cprename` VALUES ('120', 'ม.จ.', 'หม่อมเจ้า');
INSERT INTO `cprename` VALUES ('121', 'ม.ร.ว.', 'หม่อมราชวงศ์');
INSERT INTO `cprename` VALUES ('122', 'ม.ล.', 'หม่อมหลวง');
INSERT INTO `cprename` VALUES ('123', 'พระยา', 'พระยา');
INSERT INTO `cprename` VALUES ('124', 'หลวง', 'หลวง');
INSERT INTO `cprename` VALUES ('125', 'ขุน', 'ขุน');
INSERT INTO `cprename` VALUES ('126', 'หมื่น', 'หมื่น');
INSERT INTO `cprename` VALUES ('127', 'เจ้าคุณ', 'เจ้าคุณ');
INSERT INTO `cprename` VALUES ('128', 'พระวรวงศ์เธอพระองค์เจ้า', 'พระวรวงศ์เธอพระองค์เจ้า');
INSERT INTO `cprename` VALUES ('129', 'คุณ', 'คุณ');
INSERT INTO `cprename` VALUES ('130', 'คุณหญิง', 'คุณหญิง');
INSERT INTO `cprename` VALUES ('131', 'ท่านผู้หญิง ม.ล.', 'ท่านผู้หญิงหม่อมหลวง');
INSERT INTO `cprename` VALUES ('132', 'ศจ.น.พ.', 'ศาสตราจารย์นายแพทย์');
INSERT INTO `cprename` VALUES ('133', 'พ.ญ.คุณหญิง', 'แพทย์หญิงคุณหญิง');
INSERT INTO `cprename` VALUES ('134', 'น.พ.', 'นายแพทย์');
INSERT INTO `cprename` VALUES ('135', 'พ.ญ.', 'แพทย์หญิง');
INSERT INTO `cprename` VALUES ('136', 'ท.พ.', 'ทัณตแพทย์');
INSERT INTO `cprename` VALUES ('137', 'ท.ญ.', 'ทัณตแพทย์หญิง');
INSERT INTO `cprename` VALUES ('138', 'สพ.', 'สัตวแพทย์');
INSERT INTO `cprename` VALUES ('139', 'สญ.', 'สัตวแพทย์หญิง');
INSERT INTO `cprename` VALUES ('140', 'ดร.', 'ดอกเตอร์');
INSERT INTO `cprename` VALUES ('141', 'ผศ.', 'ผู้ช่วยศาสตราจารย์');
INSERT INTO `cprename` VALUES ('142', 'รศ.', 'รองศาสตราจารย์');
INSERT INTO `cprename` VALUES ('143', 'ศจ.', 'ศาสตราจารย์');
INSERT INTO `cprename` VALUES ('144', 'ภก.', 'เภสัชกรชาย');
INSERT INTO `cprename` VALUES ('145', 'ภญ.', 'เภสัชกรหญิง');
INSERT INTO `cprename` VALUES ('146', 'หม่อม', 'หม่อม');
INSERT INTO `cprename` VALUES ('147', 'รองอำมาตย์เอก', 'รองอำมาตย์เอก');
INSERT INTO `cprename` VALUES ('148', 'ท้าว', 'ท้าว');
INSERT INTO `cprename` VALUES ('149', 'เจ้า', 'เจ้า');
INSERT INTO `cprename` VALUES ('150', 'ท่านผู้หญิง', 'ท่านผู้หญิง');
INSERT INTO `cprename` VALUES ('151', 'คุณพระ', 'คุณพระ');
INSERT INTO `cprename` VALUES ('152', 'ศจ.คุณหญิง', 'ศาสตราจารย์คุณหญิง');
INSERT INTO `cprename` VALUES ('153', 'ซิสเตอร์', 'ซิสเตอร์');
INSERT INTO `cprename` VALUES ('154', 'เจ้าชาย', 'เจ้าชาย');
INSERT INTO `cprename` VALUES ('155', 'เจ้าหญิง', 'เจ้าหญิง');
INSERT INTO `cprename` VALUES ('156', 'รองเสวกตรี', 'รองเสวกตรี');
INSERT INTO `cprename` VALUES ('157', 'เสด็จเจ้า', 'เสด็จเจ้า');
INSERT INTO `cprename` VALUES ('158', 'เอกอัครราชฑูต', 'เอกอัครราชฑูต');
INSERT INTO `cprename` VALUES ('159', 'พลสารวัตร', 'พลสารวัตร');
INSERT INTO `cprename` VALUES ('160', 'สมเด็จเจ้า', 'สมเด็จเจ้า');
INSERT INTO `cprename` VALUES ('161', 'เจ้าฟ้า', 'เจ้าฟ้า');
INSERT INTO `cprename` VALUES ('162', 'รองอำมาตย์ตรี', 'รองอำมาตย์ตรี');
INSERT INTO `cprename` VALUES ('163', 'ม.จ.หญิง', 'หม่อมเจ้าหญิง');
INSERT INTO `cprename` VALUES ('164', 'ทูลกระหม่อม', 'ทูลกระหม่อม');
INSERT INTO `cprename` VALUES ('165', 'ศ.ดร.', 'ศาสตราจารย์ดอกเตอร์');
INSERT INTO `cprename` VALUES ('166', 'เจ้านาง', 'เจ้านาง');
INSERT INTO `cprename` VALUES ('167', 'จ่าสำรอง', 'จ่าสำรอง');
INSERT INTO `cprename` VALUES ('200', 'พล.อ.', 'พลเอก');
INSERT INTO `cprename` VALUES ('201', 'ว่าที่ พล.อ.', 'ว่าที่พลเอก');
INSERT INTO `cprename` VALUES ('202', 'พล.ท.', 'พลโท');
INSERT INTO `cprename` VALUES ('204', 'พล.ต.', 'พลตรี');
INSERT INTO `cprename` VALUES ('205', 'ว่าที่ พล.ต.', 'ว่าที่พลตรี');
INSERT INTO `cprename` VALUES ('206', 'พ.อ.(พิเศษ)', 'พันเอกพิเศษ');
INSERT INTO `cprename` VALUES ('207', 'ว่าที่ พ.อ.(พิเศษ)', 'ว่าที่พันเอกพิเศษ');
INSERT INTO `cprename` VALUES ('208', 'พ.อ.', 'พันเอก');
INSERT INTO `cprename` VALUES ('209', 'ว่าที่ พ.อ.', 'ว่าที่พันเอก');
INSERT INTO `cprename` VALUES ('210', 'พ.ท.', 'พันโท');
INSERT INTO `cprename` VALUES ('211', 'ว่าที่ พ.ท.', 'ว่าที่พันโท');
INSERT INTO `cprename` VALUES ('212', 'พ.ต.', 'พันตรี');
INSERT INTO `cprename` VALUES ('213', 'ว่าที่ พ.ต.', 'ว่าที่พันตรี');
INSERT INTO `cprename` VALUES ('214', 'ร.อ.', 'ร้อยเอก');
INSERT INTO `cprename` VALUES ('215', 'ว่าที่ ร.อ.', 'ว่าที่ร้อยเอก');
INSERT INTO `cprename` VALUES ('216', 'ร.ท.', 'ร้อยโท');
INSERT INTO `cprename` VALUES ('217', 'ว่าที่ ร.ท.', 'ว่าที่ร้อยโท');
INSERT INTO `cprename` VALUES ('218', 'ร.ต.', 'ร้อยตรี');
INSERT INTO `cprename` VALUES ('219', 'ว่าที่ ร.ต.', 'ว่าที่ร้อยตรี');
INSERT INTO `cprename` VALUES ('220', 'จ.ส.อ.', 'จ่าสิบเอก');
INSERT INTO `cprename` VALUES ('221', 'จ.ส.ท.', 'จ่าสิบโท');
INSERT INTO `cprename` VALUES ('222', 'จ.ส.ต.', 'จ่าสิบตรี');
INSERT INTO `cprename` VALUES ('223', 'ส.อ.', 'สิบเอก');
INSERT INTO `cprename` VALUES ('224', 'ส.ท.', 'สิบโท');
INSERT INTO `cprename` VALUES ('225', 'ส.ต.', 'สิบตรี');
INSERT INTO `cprename` VALUES ('226', 'พลฯ', 'พลทหาร');
INSERT INTO `cprename` VALUES ('227', 'นนร.', 'นักเรียนนายร้อย');
INSERT INTO `cprename` VALUES ('228', 'นนส.', 'นักเรียนนายสิบ');
INSERT INTO `cprename` VALUES ('229', 'พล.จ.', 'พลจัตวา');
INSERT INTO `cprename` VALUES ('230', 'พลฯ อาสา', 'พลฯ อาสาสมัคร');
INSERT INTO `cprename` VALUES ('231', 'ร.อ.ม.จ.', 'ร้อยเอกหม่อมเจ้า');
INSERT INTO `cprename` VALUES ('232', 'พล.ท.ม.จ.', 'พลโทหม่อมเจ้า');
INSERT INTO `cprename` VALUES ('233', 'ร.ต.ม.จ.', 'ร้อยตรีหม่อมเจ้า');
INSERT INTO `cprename` VALUES ('234', 'ร.ท.ม.จ.', 'ร้อยโทหม่อมเจ้า');
INSERT INTO `cprename` VALUES ('235', 'พ.ท.ม.จ.', 'พันโทหม่อมเจ้า');
INSERT INTO `cprename` VALUES ('236', 'พ.อ.ม.จ.', 'พันเอกหม่อมเจ้า');
INSERT INTO `cprename` VALUES ('237', 'พ.ต.ม.ร.ว.', 'พันตรีหม่อมราชวงศ์');
INSERT INTO `cprename` VALUES ('238', 'พ.ท.ม.ร.ว.', 'พันโทหม่อมราชวงศ์');
INSERT INTO `cprename` VALUES ('239', 'ส.ต.ม.ร.ว.', 'สิบตรีหม่อมราชวงศ์');
INSERT INTO `cprename` VALUES ('240', 'พ.อ.ม.ร.ว.', 'พันเอกหม่อมราชวงศ์');
INSERT INTO `cprename` VALUES ('241', 'จ.ส.อ.ม.ร.ว.', 'จ่าสิบเอกหม่อมราชวงศ์');
INSERT INTO `cprename` VALUES ('242', 'ร.อ.ม.ร.ว.', 'ร้อยเอกหม่อมราชวงศ์');
INSERT INTO `cprename` VALUES ('243', 'ร.ต.ม.ร.ว.', 'ร้อยตรีหม่อมราชวงศ์');
INSERT INTO `cprename` VALUES ('244', 'ส.อ.ม.ร.ว.', 'สิบเอกหม่อมราชวงศ์');
INSERT INTO `cprename` VALUES ('245', 'ร.ท.ม.ร.ว.', 'ร้อยโทหม่อมราชวงศ์');
INSERT INTO `cprename` VALUES ('246', 'พ.อ.(พิเศษ)ม.ร.ว.', 'พันเอก(พิเศษ)หม่อมราชวงศ์');
INSERT INTO `cprename` VALUES ('247', 'พลฯม.ล.', 'พลฯหม่อมหลวง');
INSERT INTO `cprename` VALUES ('248', 'ร.อ.ม.ล.', 'ร้อยเอกหม่อมหลวง');
INSERT INTO `cprename` VALUES ('249', 'ส.ท.ม.ล.', 'สิบโทหม่อมหลวง');
INSERT INTO `cprename` VALUES ('250', 'พล.ท.ม.ล.', 'พลโทหม่อมหลวง');
INSERT INTO `cprename` VALUES ('251', 'ร.ท.ม.ล.', 'ร้อยโทหม่อมหลวง');
INSERT INTO `cprename` VALUES ('252', 'ร.ต.ม.ล.', 'ร้อยตรีหม่อมหลวง');
INSERT INTO `cprename` VALUES ('253', 'ส.อ.ม.ล.', 'สิบเอกหม่อมหลวง');
INSERT INTO `cprename` VALUES ('254', 'พล.ต.ม.ล.', 'พลตรีหม่อมหลวง');
INSERT INTO `cprename` VALUES ('255', 'พ.ต.ม.ล.', 'พันตรีหม่อมหลวง');
INSERT INTO `cprename` VALUES ('256', 'พ.อ.ม.ล.', 'พันเอกหม่อมหลวง');
INSERT INTO `cprename` VALUES ('257', 'พ.ท.ม.ล.', 'พันโทหม่อมหลวง');
INSERT INTO `cprename` VALUES ('258', 'จ.ส.ต.ม.ล.', 'จ่าสิบตรีหม่อมหลวง');
INSERT INTO `cprename` VALUES ('259', 'นนร.ม.ล.', 'นักเรียนนายร้อยหม่อมหลวง');
INSERT INTO `cprename` VALUES ('260', 'ว่าที่ร.ต.ม.ล.', 'ว่าที่ร้อยตรีหม่อมหลวง');
INSERT INTO `cprename` VALUES ('261', 'จ.ส.อ.ม.ล.', 'จ่าสิบเอกหม่อมหลวง');
INSERT INTO `cprename` VALUES ('262', 'ร.อ.น.พ.', 'ร้อยเอกนายแพทย์');
INSERT INTO `cprename` VALUES ('263', 'ร.อ.พ.ญ.', 'ร้อยเอกแพทย์หญิง');
INSERT INTO `cprename` VALUES ('264', 'ร.ท.น.พ.', 'ร้อยโทนายแพทย์');
INSERT INTO `cprename` VALUES ('265', 'พ.ต.น.พ.', 'พันตรีนายแพทย์');
INSERT INTO `cprename` VALUES ('266', 'ว่าที่ ร.ท.น.พ.', 'ว่าที่ร้อยโทนายแพทย์');
INSERT INTO `cprename` VALUES ('267', 'พ.อ.น.พ.', 'พันเอกนายแพทย์');
INSERT INTO `cprename` VALUES ('268', 'ร.ต.น.พ.', 'ร้อยตรีนายแพทย์');
INSERT INTO `cprename` VALUES ('269', 'ร.ท.พ.ญ.', 'ร้อยโทแพทย์หญิง');
INSERT INTO `cprename` VALUES ('270', 'พล.ต.น.พ.', 'พลตรีนายแพทย์');
INSERT INTO `cprename` VALUES ('271', 'พ.ท.น.พ.', 'พันโทนายแพทย์');
INSERT INTO `cprename` VALUES ('272', 'จอมพล', 'จอมพล');
INSERT INTO `cprename` VALUES ('273', 'พ.ท.หลวง', 'พันโทหลวง');
INSERT INTO `cprename` VALUES ('274', 'พ.ต.พระเจ้าวรวงศ์เธอพระองค์เจ้า', 'พันตรีพระเจ้าวรวงศ์เธอพระองค์เจ้า');
INSERT INTO `cprename` VALUES ('275', 'ศจ.พ.อ.', 'ศาสตราจารย์พันเอก');
INSERT INTO `cprename` VALUES ('276', 'พ.ต.หลวง', 'พันตรีหลวง');
INSERT INTO `cprename` VALUES ('277', 'พล.ท.หลวง', 'พลโทหลวง');
INSERT INTO `cprename` VALUES ('278', 'ร.ท.ดร.', 'ร้อยโทดอกเตอร์');
INSERT INTO `cprename` VALUES ('279', 'ร.อ.ดร.', 'ร้อยเอกดอกเตอร์');
INSERT INTO `cprename` VALUES ('280', 'ส.ห.', 'สารวัตรทหาร');
INSERT INTO `cprename` VALUES ('281', 'ร.ต.ดร.', 'ร้อยตรีดอกเตอร์');
INSERT INTO `cprename` VALUES ('282', 'พ.ต.คุณหญิง', 'พันตรีคุณหญิง');
INSERT INTO `cprename` VALUES ('283', 'จ.ส.ต.ม.ร.ว.', 'จ่าสิบตรีหม่อมราชวงศ์');
INSERT INTO `cprename` VALUES ('284', 'พล.จ.หลวง', 'พลจัตวาหลวง');
INSERT INTO `cprename` VALUES ('285', 'พล.ต.ม.ร.ว.', 'พลตรีหม่อมราชวงศ์');
INSERT INTO `cprename` VALUES ('286', 'พ.ต.พระเจ้าวรวงศ์เธอพระองค์', 'พันตรีพระเจ้าวรวงศ์เธอพระองค์');
INSERT INTO `cprename` VALUES ('287', 'ท่านผู้หญิง ม.ร.ว.', 'ท่านผู้หญิงหม่อมราชวงศ์');
INSERT INTO `cprename` VALUES ('288', 'ศจ.ร.อ.', 'ศาสตราจารย์ร้อยเอก');
INSERT INTO `cprename` VALUES ('289', 'พ.ท.คุณหญิง', 'พันโทคุณหญิง');
INSERT INTO `cprename` VALUES ('290', 'ร.ต.พ.ญ.', 'ร้อยตรีแพทย์หญิง');
INSERT INTO `cprename` VALUES ('291', 'พล.อ.มล.', 'พลเอกหม่อมหลวง');
INSERT INTO `cprename` VALUES ('292', 'ว่าที่ ร.ต.ม.ร.ว.', 'ว่าที่ร้อยตรีหม่อมราชวงศ์');
INSERT INTO `cprename` VALUES ('293', 'พ.อ.หญิง คุณหญิง', 'พันเอกหญิงคุณหญิง');
INSERT INTO `cprename` VALUES ('294', 'จ.ส.อ.พิเศษ', 'จ่าสิบเอกพิเศษ');
INSERT INTO `cprename` VALUES ('351', 'พล.ร.อ.', 'พลเรือเอก');
INSERT INTO `cprename` VALUES ('352', 'ว่าที่ พล.ร.อ.', 'ว่าที่พลเรือเอก');
INSERT INTO `cprename` VALUES ('353', 'พล.ร.ท.', 'พลเรือโท');
INSERT INTO `cprename` VALUES ('354', 'ว่าที่ พล.ร.ท.', 'ว่าที่พลเรือโท');
INSERT INTO `cprename` VALUES ('355', 'พล.ร.ต.', 'พลเรือตรี');
INSERT INTO `cprename` VALUES ('356', 'ว่าที่ พล.ร.ต.', 'ว่าที่พลเรือตรี');
INSERT INTO `cprename` VALUES ('357', 'น.อ.พิเศษ', 'นาวาเอกพิเศษ');
INSERT INTO `cprename` VALUES ('358', 'ว่าที่ น.อ.พิเศษ', 'ว่าที่นาวาเอกพิเศษ');
INSERT INTO `cprename` VALUES ('359', 'น.อ.', 'นาวาเอก');
INSERT INTO `cprename` VALUES ('360', 'ว่าที่ น.อ.', 'ว่าที่นาวาเอก');
INSERT INTO `cprename` VALUES ('361', 'น.ท.', 'นาวาโท');
INSERT INTO `cprename` VALUES ('362', 'ว่าที่ น.ท.', 'ว่าที่นาวาโท');
INSERT INTO `cprename` VALUES ('363', 'น.ต.', 'นาวาตรี');
INSERT INTO `cprename` VALUES ('364', 'ว่าที่ น.ต.', 'ว่าที่นาวาตรี');
INSERT INTO `cprename` VALUES ('365', 'ร.อ.', 'เรือเอก');
INSERT INTO `cprename` VALUES ('366', 'ว่าที่ ร.อ.', 'ว่าที่เรือเอก');
INSERT INTO `cprename` VALUES ('367', 'ร.ท.', 'เรือโท');
INSERT INTO `cprename` VALUES ('368', 'ว่าที่ ร.ท.', 'ว่าที่เรือโท');
INSERT INTO `cprename` VALUES ('369', 'ร.ต.', 'เรือตรี');
INSERT INTO `cprename` VALUES ('370', 'ว่าที่ ร.ต.', 'ว่าที่เรือตรี');
INSERT INTO `cprename` VALUES ('371', 'พ.จ.อ.', 'พันจ่าเอก');
INSERT INTO `cprename` VALUES ('372', 'พ.จ.ท.', 'พันจ่าโท');
INSERT INTO `cprename` VALUES ('373', 'พ.จ.ต.', 'พันจ่าตรี');
INSERT INTO `cprename` VALUES ('374', 'จ.อ.', 'จ่าเอก');
INSERT INTO `cprename` VALUES ('375', 'จ.ท.', 'จ่าโท');
INSERT INTO `cprename` VALUES ('376', 'จ.ต.', 'จ่าตรี');
INSERT INTO `cprename` VALUES ('377', 'พลฯ', 'พลฯทหารเรือ');
INSERT INTO `cprename` VALUES ('378', 'นนร.', 'นักเรียนนายเรือ');
INSERT INTO `cprename` VALUES ('379', 'นรจ.', 'นักเรียนจ่าทหารเรือ');
INSERT INTO `cprename` VALUES ('380', 'พล.ร.จ.', 'พลเรือจัตวา');
INSERT INTO `cprename` VALUES ('381', 'น.ท.ม.จ.', 'นาวาโทหม่อมเจ้า');
INSERT INTO `cprename` VALUES ('382', 'น.อ.ม.จ.', 'นาวาเอกหม่อมเจ้า');
INSERT INTO `cprename` VALUES ('383', 'น.ต.ม.จ.', 'นาวาตรีหม่อมเจ้า');
INSERT INTO `cprename` VALUES ('384', 'พล.ร.ต.ม.ร.ว.', 'พลเรือตรีหม่อมราชวงศ์');
INSERT INTO `cprename` VALUES ('385', 'น.อ.ม.ร.ว.', 'นาวาเอกหม่อมราชวงศ์');
INSERT INTO `cprename` VALUES ('386', 'น.ท.ม.ร.ว.', 'นาวาโทหม่อมราชวงศ์');
INSERT INTO `cprename` VALUES ('387', 'น.ต.ม.ร.ว.', 'นาวาตรีหม่อมราชวงศ์');
INSERT INTO `cprename` VALUES ('388', 'น.ท.ม.ล.', 'นาวาโทหม่อมหลวง');
INSERT INTO `cprename` VALUES ('389', 'น.ต.ม.ล.', 'นาวาตรีหม่อมหลวง');
INSERT INTO `cprename` VALUES ('390', 'พ.จ.อ.ม.ล.', 'พันจ่าเอกหม่อมหลวง');
INSERT INTO `cprename` VALUES ('391', 'น.ต.พ.ญ.', 'นาวาตรีแพทย์หญิง');
INSERT INTO `cprename` VALUES ('392', 'น.อ.หลวง', 'นาวาอากาศเอกหลวง');
INSERT INTO `cprename` VALUES ('393', 'พล.ร.ต.ม.จ.', 'พลเรือตรีหม่อมเจ้า');
INSERT INTO `cprename` VALUES ('395', 'น.ต.น.พ.', 'นาวาตรีนายแพทย์');
INSERT INTO `cprename` VALUES ('396', 'พล.ร.ต.ม.ล.', 'พลเรือตรีหม่อมหลวง');
INSERT INTO `cprename` VALUES ('500', 'พล.อ.อ.', 'พลอากาศเอก');
INSERT INTO `cprename` VALUES ('501', 'ว่าที่ พล.อ.อ.', 'ว่าที่พลอากาศเอก');
INSERT INTO `cprename` VALUES ('502', 'พล.อ.ท.', 'พลอากาศโท');
INSERT INTO `cprename` VALUES ('503', 'ว่าที่ พล.อ.ท.', 'ว่าที่พลอากาศโท');
INSERT INTO `cprename` VALUES ('504', 'พล.อ.ต.', 'พลอากาศตรี');
INSERT INTO `cprename` VALUES ('505', 'ว่าที่ พล.อ.ต.', 'ว่าที่พลอากาศตรี');
INSERT INTO `cprename` VALUES ('506', 'น.อ.พิเศษ', 'นาวาอากาศเอกพิเศษ');
INSERT INTO `cprename` VALUES ('507', 'ว่าที่ น.อ.พิเศษ', 'ว่าที่นาวาอากาศเอกพิเศษ');
INSERT INTO `cprename` VALUES ('508', 'น.อ.', 'นาวาอากาศเอก');
INSERT INTO `cprename` VALUES ('509', 'ว่าที่ น.อ.', 'ว่าที่นาวาอากาศเอก');
INSERT INTO `cprename` VALUES ('510', 'น.ท.', 'นาวาอากาศโท');
INSERT INTO `cprename` VALUES ('511', 'ว่าที่ น.ท.', 'ว่าที่นาวาอากาศโท');
INSERT INTO `cprename` VALUES ('512', 'น.ต.', 'นาวาอากาศตรี');
INSERT INTO `cprename` VALUES ('513', 'ว่าที่ น.ต.', 'ว่าที่นาวาอากาศตรี');
INSERT INTO `cprename` VALUES ('514', 'ร.อ.', 'เรืออากาศเอก');
INSERT INTO `cprename` VALUES ('515', 'ว่าที่ ร.อ.', 'ว่าที่เรืออากาศเอก');
INSERT INTO `cprename` VALUES ('516', 'ร.ท.', 'เรืออากาศโท');
INSERT INTO `cprename` VALUES ('517', 'ว่าที่ ร.ท.', 'ว่าที่เรืออากาศโท');
INSERT INTO `cprename` VALUES ('518', 'ร.ต.', 'เรืออากาศตรี');
INSERT INTO `cprename` VALUES ('519', 'ว่าที่ ร.ต.', 'ว่าที่เรืออากาศตรี');
INSERT INTO `cprename` VALUES ('520', 'พ.อ.อ.', 'พันจ่าอากาศเอก');
INSERT INTO `cprename` VALUES ('521', 'พ.อ.ท.', 'พันจ่าอากาศโท');
INSERT INTO `cprename` VALUES ('522', 'พ.อ.ต.', 'พันจ่าอากาศตรี');
INSERT INTO `cprename` VALUES ('523', 'จ.อ.', 'จ่าอากาศเอก');
INSERT INTO `cprename` VALUES ('524', 'จ.ท.', 'จ่าอากาศโท');
INSERT INTO `cprename` VALUES ('525', 'จ.ต.', 'จ่าอากาศตรี');
INSERT INTO `cprename` VALUES ('526', 'พลฯ', 'พลฯทหารอากาศ');
INSERT INTO `cprename` VALUES ('527', 'นนอ.', 'นักเรียนนายเรืออากาศ');
INSERT INTO `cprename` VALUES ('528', 'นจอ.', 'นักเรียนจ่าอากาศ');
INSERT INTO `cprename` VALUES ('529', 'น.พ.อ.', 'นักเรียนพยาบาลทหารอากาศ');
INSERT INTO `cprename` VALUES ('530', 'พ.อ.อ.ม.ร.ว.', 'พันอากาศเอกหม่อมราชวงศ์');
INSERT INTO `cprename` VALUES ('531', 'พล.อ.ต.ม.ร.ว.', 'พลอากาศตรีหม่อมราชวงศ์');
INSERT INTO `cprename` VALUES ('532', 'พล.อ.ท.ม.ล.', 'พลอากาศโทหม่อมหลวง');
INSERT INTO `cprename` VALUES ('533', 'ร.ท.ขุน', 'เรืออากาศโทขุน');
INSERT INTO `cprename` VALUES ('534', 'พ.อ.อ.ม.ล.', 'พันจ่าอากาศเอกหม่อมหลวง');
INSERT INTO `cprename` VALUES ('535', 'ร.อ.น.พ.', 'เรืออากาศเอกนายแพทย์');
INSERT INTO `cprename` VALUES ('536', 'พล.อ.อ.ม.ร.ว.', 'พลอากาศเอกหม่อมราชวงศ์');
INSERT INTO `cprename` VALUES ('537', 'พล.อ.ต.ม.ล.', 'พลอากาศตรีหม่อมหลวง');
INSERT INTO `cprename` VALUES ('538', 'พล.อ.จ.', 'พลอากาศจัตวา');
INSERT INTO `cprename` VALUES ('539', 'พล.อ.ท.ม.ร.ว.', 'พลอากาศโทหม่อมราชวงศ์');
INSERT INTO `cprename` VALUES ('540', 'น.อ.ม.ล.', 'นาวาอากาศเอกหม่อมหลวง');
INSERT INTO `cprename` VALUES ('606', 'พระครูพิบูลสมณธรรม', 'พระครูพิบูลสมณธรรม');
INSERT INTO `cprename` VALUES ('651', 'พล.ต.อ.', 'พลตำรวจเอก');
INSERT INTO `cprename` VALUES ('652', 'ว่าที่ พล.ต.อ.', 'ว่าที่พลตำรวจเอก');
INSERT INTO `cprename` VALUES ('653', 'พล.ต.ท.', 'พลตำรวจโท');
INSERT INTO `cprename` VALUES ('654', 'ว่าที่ พล.ต.ท.', 'ว่าที่พลตำรวจโท');
INSERT INTO `cprename` VALUES ('655', 'พล.ต.ต.', 'พลตำรวจตรี');
INSERT INTO `cprename` VALUES ('656', 'ว่าที่ พล.ต.ต.', 'ว่าที่พลตำรวจตรี');
INSERT INTO `cprename` VALUES ('657', 'พล.ต.จ.', 'พลตำรวจจัตวา');
INSERT INTO `cprename` VALUES ('658', 'ว่าที่พล.ต.จ.', 'ว่าที่พลตำรวจจัตวา');
INSERT INTO `cprename` VALUES ('659', 'พ.ต.อ. (พิเศษ)', 'พันตำรวจเอก (พิเศษ)');
INSERT INTO `cprename` VALUES ('660', 'ว่าที่ พ.ต.อ.พิเศษ', 'ว่าที่พันตำรวจเอก(พิเศษ)');
INSERT INTO `cprename` VALUES ('661', 'พ.ต.อ.', 'พันตำรวจเอก');
INSERT INTO `cprename` VALUES ('662', 'ว่าที่ พ.ต.อ.', 'ว่าที่พันตำรวจเอก');
INSERT INTO `cprename` VALUES ('663', 'พ.ต.ท.', 'พันตำรวจโท');
INSERT INTO `cprename` VALUES ('664', 'ว่าที่ พ.ต.ท.', 'ว่าที่พันตำรวจโท');
INSERT INTO `cprename` VALUES ('665', 'พ.ต.ต.', 'พันตำรวจตรี');
INSERT INTO `cprename` VALUES ('666', 'ว่าที่ พ.ต.ต.', 'ว่าที่พันตำรวจตรี');
INSERT INTO `cprename` VALUES ('667', 'ร.ต.อ.', 'ร้อยตำรวจเอก');
INSERT INTO `cprename` VALUES ('668', 'ว่าที่ ร.ต.อ.', 'ว่าที่ร้อยตำรวจเอก');
INSERT INTO `cprename` VALUES ('669', 'ร.ต.ท.', 'ร้อยตำรวจโท');
INSERT INTO `cprename` VALUES ('670', 'ว่าที่ ร.ต.ท.', 'ว่าที่ร้อยตำรวจโท');
INSERT INTO `cprename` VALUES ('671', 'ร.ต.ต.', 'ร้อยตำรวจตรี');
INSERT INTO `cprename` VALUES ('672', 'ว่าที่ ร.ต.ต.', 'ว่าที่ร้อยตำรวจตรี');
INSERT INTO `cprename` VALUES ('673', 'ด.ต.', 'นายดาบตำรวจ');
INSERT INTO `cprename` VALUES ('674', 'จ.ส.ต.', 'จ่าสิบตำรวจ');
INSERT INTO `cprename` VALUES ('675', 'ส.ต.อ.', 'สิบตำรวจเอก');
INSERT INTO `cprename` VALUES ('676', 'ส.ต.ท.', 'สิบตำรวจโท');
INSERT INTO `cprename` VALUES ('677', 'ส.ต.ต.', 'สิบตำรวจตรี');
INSERT INTO `cprename` VALUES ('678', 'นรต.', 'นักเรียนนายร้อยตำรวจ');
INSERT INTO `cprename` VALUES ('679', 'นสต.', 'นักเรียนนายสิบตำรวจ');
INSERT INTO `cprename` VALUES ('680', 'นพต.', 'นักเรียนพลตำรวจ');
INSERT INTO `cprename` VALUES ('681', 'พลฯ', 'พลตำรวจ');
INSERT INTO `cprename` VALUES ('682', 'พลฯพิเศษ', 'พลตำรวจพิเศษ');
INSERT INTO `cprename` VALUES ('683', 'พลฯอาสา', 'พลตำรวจอาสาสมัคร');
INSERT INTO `cprename` VALUES ('684', 'พลฯสำรอง', 'พลตำรวจสำรอง');
INSERT INTO `cprename` VALUES ('685', 'พลฯสำรองพิเศษ', 'พลตำรวจสำรองพิเศษ');
INSERT INTO `cprename` VALUES ('686', 'พลฯสมัคร', 'พลตำรวจสมัคร');
INSERT INTO `cprename` VALUES ('687', 'อส.', 'สมาชิกอาสารักษาดินแดน');
INSERT INTO `cprename` VALUES ('688', 'ก.ญ.', 'นายกองใหญ่');
INSERT INTO `cprename` VALUES ('689', 'ก.อ.', 'นายกองเอก');
INSERT INTO `cprename` VALUES ('690', 'ก.ท.', 'นายกองโท');
INSERT INTO `cprename` VALUES ('691', 'ก.ต.', 'นายกองตรี');
INSERT INTO `cprename` VALUES ('692', 'มว.อ.', 'นายหมวดเอก');
INSERT INTO `cprename` VALUES ('693', 'มว.ท.', 'นายหมวดโท');
INSERT INTO `cprename` VALUES ('694', 'มว.ต.', 'นายหมวดตรี');
INSERT INTO `cprename` VALUES ('695', 'ม.ญ.', 'นายหมู่ใหญ่');
INSERT INTO `cprename` VALUES ('696', 'ม.อ.', 'นายหมู่เอก');
INSERT INTO `cprename` VALUES ('697', 'ม.ท.', 'นายหมู่โท');
INSERT INTO `cprename` VALUES ('698', 'ม.ต.', 'นายหมู่ตรี');
INSERT INTO `cprename` VALUES ('699', 'สมาชิกเอก', 'สมาชิกเอก');
INSERT INTO `cprename` VALUES ('700', 'สมาชิกโท', 'สมาชิกโท');
INSERT INTO `cprename` VALUES ('701', 'สมาชิกตรี', 'สมาชิกตรี');
INSERT INTO `cprename` VALUES ('702', 'อส.ทพ.', 'อาสาสมัครทหารพราน');
INSERT INTO `cprename` VALUES ('703', 'พ.ต.ท.ม.จ.', 'พันตำรวจโทหม่อมเจ้า');
INSERT INTO `cprename` VALUES ('704', 'พ.ต.อ.ม.จ.', 'พันตำรวจเอกหม่อมเจ้า');
INSERT INTO `cprename` VALUES ('705', 'นรต.ม.จ.', 'นักเรียนนายร้อยตำรวจหม่อมเจ้า');
INSERT INTO `cprename` VALUES ('706', 'พล.ต.ต.ม.ร.ว.', 'พลตำรวจตรีหม่อมราชวงศ์');
INSERT INTO `cprename` VALUES ('707', 'พ.ต.ต.ม.ร.ว.', 'พันตำรวจตรีหม่อมราชวงศ์');
INSERT INTO `cprename` VALUES ('708', 'พ.ต.ท.ม.ร.ว.', 'พันตำรวจโทหม่อมราชวงศ์');
INSERT INTO `cprename` VALUES ('709', 'พ.ต.อ.ม.ร.ว.', 'พันตำรวจเอกหม่อมราชวงศ์');
INSERT INTO `cprename` VALUES ('710', 'ร.ต.อ.ม.ร.ว.', 'ร้อยตำรวจเอกหม่อมราชวงศ์');
INSERT INTO `cprename` VALUES ('711', 'ส.ต.อ.ม.ล.', 'สิบตำรวจเอกหม่อมหลวง');
INSERT INTO `cprename` VALUES ('712', 'พ.ต.อ.ม.ล.', 'พันตำรวจเอกหม่อมหลวง');
INSERT INTO `cprename` VALUES ('713', 'พ.ต.ท.ม.ล.', 'พันตำรวจโทหม่อมหลวง');
INSERT INTO `cprename` VALUES ('714', 'นรต.ม.ล.', 'นักเรียนนายร้อยตำรวจหม่อมหลวง');
INSERT INTO `cprename` VALUES ('715', 'ร.ต.ท.ม.ล.', 'ร้อยตำรวจโทหม่อมหลวง');
INSERT INTO `cprename` VALUES ('716', 'ด.ต.ม.ล.', 'นายดาบตำรวจหม่อมหลวง');
INSERT INTO `cprename` VALUES ('717', 'พ.ต.ต.ม.ล.', 'พันตำรวจตรีหม่อมหลวง');
INSERT INTO `cprename` VALUES ('718', 'ศจ.น.พ.พ.ต.อ.', 'ศาสตราจารย์นายแพทย์พันตำรวจเอก');
INSERT INTO `cprename` VALUES ('719', 'พ.ต.ท.น.พ.', 'พันตำรวจโทนายแพทย์');
INSERT INTO `cprename` VALUES ('720', 'ร.ต.ท.น.พ.', 'ร้อยตำรวจโทนายแพทย์');
INSERT INTO `cprename` VALUES ('721', 'ร.ต.อ.น.พ.', 'ร้อยตำรวจเอกนายแพทย์');
INSERT INTO `cprename` VALUES ('722', 'พ.ต.ต.นพ.', 'พันตำรวจตรีนายแพทย์');
INSERT INTO `cprename` VALUES ('723', 'พ.ต.อ.น.พ.', 'พันตำรวจเอกนายแพทย์');
INSERT INTO `cprename` VALUES ('724', 'พ.ต.ต.หลวง', 'พันตำรวจตรีหลวง');
INSERT INTO `cprename` VALUES ('725', 'ร.ต.ท.ดร.', 'ร้อยตำรวจโทดอกเตอร์');
INSERT INTO `cprename` VALUES ('726', 'พ.ต.อ.ดร.', 'พันตำรวจเอกดอกเตอร์');
INSERT INTO `cprename` VALUES ('727', 'ร.ต.อ.ม.ล.', 'ร้อยตำรวจเอกหม่อมหลวง');
INSERT INTO `cprename` VALUES ('729', 'พ.ต.อ.หญิง ท่านผู้หญิง', 'พันตำรวจเอกหญิง ท่านผู้หญิง');
INSERT INTO `cprename` VALUES ('730', 'พล.ต.ต.ม.ล.', 'พลตำรวจตรีหม่อมหลวง');
INSERT INTO `cprename` VALUES ('731', 'พล.ต.หญิง คุณหญิง', 'พลตรีหญิง คุณหญิง');
INSERT INTO `cprename` VALUES ('732', 'ว่าที่ ส.อ.', 'ว่าที่สิบเอก');
INSERT INTO `cprename` VALUES ('733', 'พล.ต.อ.ดร.', 'พลตำรวจเอกดอกเตอร์');
INSERT INTO `cprename` VALUES ('800', 'สมเด็จพระสังฆราชเจ้า', 'สมเด็จพระสังฆราชเจ้า');
INSERT INTO `cprename` VALUES ('801', 'สมเด็จพระสังฆราช', 'สมเด็จพระสังฆราช');
INSERT INTO `cprename` VALUES ('802', 'สมเด็จพระราชาคณะ', 'สมเด็จพระราชาคณะ');
INSERT INTO `cprename` VALUES ('803', 'รองสมเด็จพระราชาคณะ', 'รองสมเด็จพระราชาคณะ');
INSERT INTO `cprename` VALUES ('804', 'พระราชาคณะ', 'พระราชาคณะ');
INSERT INTO `cprename` VALUES ('805', 'พระเปรียญธรรม', 'พระเปรียญธรรม');
INSERT INTO `cprename` VALUES ('806', 'พระหิรัญยบัฏ', 'พระหิรัญยบัฏ');
INSERT INTO `cprename` VALUES ('807', 'พระสัญญาบัตร', 'พระสัญญาบัตร');
INSERT INTO `cprename` VALUES ('808', 'พระราช', 'พระราช');
INSERT INTO `cprename` VALUES ('809', 'พระเทพ', 'พระเทพ');
INSERT INTO `cprename` VALUES ('810', 'พระปลัดขวา', 'พระปลัดขวา');
INSERT INTO `cprename` VALUES ('811', 'พระปลัดซ้าย', 'พระปลัดซ้าย');
INSERT INTO `cprename` VALUES ('812', 'พระครูปลัด', 'พระครูปลัด');
INSERT INTO `cprename` VALUES ('813', 'พระครูปลัดสุวัฒนญาณคุณ', 'พระครูปลัดสุวัฒนญาณคุณ');
INSERT INTO `cprename` VALUES ('814', 'พระครูปลัดอาจารย์วัฒน์', 'พระครูปลัดอาจารย์วัฒน์');
INSERT INTO `cprename` VALUES ('815', 'พระครูปลัดวิมลสิริวัฒน์', 'พระครูวิมลสิริวัฒน์');
INSERT INTO `cprename` VALUES ('816', 'พระสมุห์', 'พระสมุห์');
INSERT INTO `cprename` VALUES ('817', 'พระครูสมุห์', 'พระครูสมุห์');
INSERT INTO `cprename` VALUES ('818', 'พระครู', 'พระครู');
INSERT INTO `cprename` VALUES ('819', 'พระครูใบฎีกา', 'พระครูใบฎีกา');
INSERT INTO `cprename` VALUES ('820', 'พระครูธรรมธร', 'พระครูธรรมธร');
INSERT INTO `cprename` VALUES ('821', 'พระครูวิมลภาณ', 'พระครูวิมลภาณ');
INSERT INTO `cprename` VALUES ('822', 'พระครูศัพทมงคล', 'พระครูศัพทมงคล');
INSERT INTO `cprename` VALUES ('823', 'พระครูสังฆภารวิชัย', 'พระครูสังฆภารวิชัย');
INSERT INTO `cprename` VALUES ('824', 'พระครูสังฆรักษ์', 'พระครูสังฆรักษ์');
INSERT INTO `cprename` VALUES ('825', 'พระครูสังฆวิชัย', 'พระครูสังฆวิชัย');
INSERT INTO `cprename` VALUES ('826', 'พระครูสังฆวิชิต', 'พระครูสังฆวิชิต');
INSERT INTO `cprename` VALUES ('827', 'พระปิฎก', 'พระปิฎก');
INSERT INTO `cprename` VALUES ('828', 'พระปริยัติ', 'พระปริยัติ');
INSERT INTO `cprename` VALUES ('829', 'เจ้าอธิการ', 'เจ้าอธิการ');
INSERT INTO `cprename` VALUES ('830', 'พระอธิการ', 'พระอธิการ');
INSERT INTO `cprename` VALUES ('831', 'พระ', 'พระ');
INSERT INTO `cprename` VALUES ('832', 'ส.ณ.', 'สามเณร');
INSERT INTO `cprename` VALUES ('833', 'พระปลัด', 'พระปลัด');
INSERT INTO `cprename` VALUES ('834', 'สมเด็จพระอริยวงศาคตญาณ', 'สมเด็จพระอริยวงศาคตญาณ');
INSERT INTO `cprename` VALUES ('835', 'พระคาร์ดินัล', 'พระคาร์ดินัล');
INSERT INTO `cprename` VALUES ('836', 'พระสังฆราช', 'พระสังฆราช');
INSERT INTO `cprename` VALUES ('837', 'พระคุณเจ้า', 'พระคุณเจ้า');
INSERT INTO `cprename` VALUES ('838', 'บาทหลวง', 'บาทหลวง');
INSERT INTO `cprename` VALUES ('839', 'พระมหา', 'พระมหา');
INSERT INTO `cprename` VALUES ('840', 'พระราชปัญญา', 'พระราชปัญญา');
INSERT INTO `cprename` VALUES ('841', 'ภาราดา', 'ภาราดา');
INSERT INTO `cprename` VALUES ('842', 'พระศรีปริยัติธาดา', 'พระศรีปริยัติธาดา');
INSERT INTO `cprename` VALUES ('843', 'พระญาณโศภณ', 'พระญาณโศภณ');
INSERT INTO `cprename` VALUES ('844', 'สมเด็จพระมหาวีรวงศ์', 'สมเด็จพระมหาวีรวงศ์');
INSERT INTO `cprename` VALUES ('845', 'พระโสภณธรรมาภรณ์', 'พระโสภณธรรมาภรณ์');
INSERT INTO `cprename` VALUES ('846', 'พระวิริวัฒน์วิสุทธิ์', 'พระวิริวัฒน์วิสุทธิ์');
INSERT INTO `cprename` VALUES ('847', 'พระญาณ', 'พระญาณ');
INSERT INTO `cprename` VALUES ('848', 'พระอัครสังฆราช', 'พระอัครสังฆราช');
INSERT INTO `cprename` VALUES ('849', 'พระธรรม', 'พระธรรม');
INSERT INTO `cprename` VALUES ('850', 'พระสาสนโสภณ', 'พระสาสนโสภณ');
INSERT INTO `cprename` VALUES ('851', 'พระธรรมโสภณ', 'พระธรรมโสภณ');
INSERT INTO `cprename` VALUES ('852', 'พระอุดมสารโสภณ', 'พระอุดมสารโสภณ');
INSERT INTO `cprename` VALUES ('853', 'พระครูวิมลญาณโสภณ', 'พระครูวิมลญาณโสภณ');
INSERT INTO `cprename` VALUES ('854', 'พระครูปัญญาภรณโสภณ', 'พระครูปัญญาภรณโสภณ');
INSERT INTO `cprename` VALUES ('855', 'พระครูโสภณปริยัติคุณ', 'พระครูโสภณปริยัติคุณ');
INSERT INTO `cprename` VALUES ('856', 'พระอธิธรรม', 'พระอธิธรรม');
INSERT INTO `cprename` VALUES ('857', 'พระราชญาณ', 'พระราชญาณ');
INSERT INTO `cprename` VALUES ('858', 'พระสุธีวัชโรดม', 'พระสุธีวัชโรดม');
INSERT INTO `cprename` VALUES ('859', 'รองเจ้าอธิการ', 'รองเจ้าอธิการ');
INSERT INTO `cprename` VALUES ('860', 'พระครูวินัยธร', 'พระครูวินัยธร');
INSERT INTO `cprename` VALUES ('861', 'พระศรีวชิราภรณ์', 'พระศรีวชิราภรณ์');
INSERT INTO `cprename` VALUES ('862', 'พระราชบัณฑิต', 'พระราชบัณฑิต');
INSERT INTO `cprename` VALUES ('863', 'แม่ชี', 'แม่ชี');
INSERT INTO `cprename` VALUES ('864', 'นักบวช', 'นักบวช');
INSERT INTO `cprename` VALUES ('865', 'พระรัตน', 'พระรัตน');
INSERT INTO `cprename` VALUES ('866', 'พระโสภณปริยัติธรรม', 'พระโสภณปริยัติธรรม');
INSERT INTO `cprename` VALUES ('867', 'พระครูวิศาลปัญญาคุณ', 'พระครูวิศาลปัญญาคุณ');
INSERT INTO `cprename` VALUES ('868', 'พระศรีปริยัติโมลี', 'พระศรีปริยัติโมลี');
INSERT INTO `cprename` VALUES ('869', 'พระครูวัชรสีลาภรณ์', 'พระครูวัชรสีลาภรณ์');
INSERT INTO `cprename` VALUES ('870', 'พระครูพิพัฒน์บรรณกิจ', 'พระครูพิพัฒน์บรรณกิจ');
INSERT INTO `cprename` VALUES ('871', 'พระครูวิบูลธรรมกิจ', 'พระครูวิบูลธรรมกิจ');
INSERT INTO `cprename` VALUES ('872', 'พระครูพัฒนสารคุณ', 'พระครูพัฒนสารคุณ');
INSERT INTO `cprename` VALUES ('873', 'พระครูสุวรรณพัฒนคุณ', 'พระครูสุวรรณพัฒนคุณ');
INSERT INTO `cprename` VALUES ('874', 'พระครูพรหมวีรสุนทร', 'พระครูพรหมวีรสุนทร');
INSERT INTO `cprename` VALUES ('875', 'พระครูอุปถัมภ์นันทกิจ', 'พระครูอุปถัมภ์นันทกิจ');
INSERT INTO `cprename` VALUES ('876', 'พระครูวิจารณ์สังฆกิจ', 'พระครูวิจารณ์สังฆกิจ');
INSERT INTO `cprename` VALUES ('877', 'พระครูวิมลสารวิสุทธิ์', 'พระครูวิมลสารวิสุทธิ์');
INSERT INTO `cprename` VALUES ('878', 'พระครูไพศาลศุภกิจ', 'พระครูไพศาลศุภกิจ');
INSERT INTO `cprename` VALUES ('879', 'พระครูโอภาสธรรมพิมล', 'พระครูโอภาสธรรมพิมล');
INSERT INTO `cprename` VALUES ('880', 'พระครูพิพิธวรคุณ', 'พระครูพิพิธวรคุณ');
INSERT INTO `cprename` VALUES ('881', 'พระครูสุนทรปภากร', 'พระครูสุนทรปภากร');
INSERT INTO `cprename` VALUES ('882', 'พระครูสิริชัยสถิต', 'พระครูสิริชัยสถิต');
INSERT INTO `cprename` VALUES ('883', 'พระครูเกษมธรรมานันท์', 'พระครูเกษมธรรมานันท์');
INSERT INTO `cprename` VALUES ('884', 'พระครูถาวรสันติคุณ', 'พระครูถาวรสันติคุณ');
INSERT INTO `cprename` VALUES ('885', 'พระครูวิสุทธาจารวิมล', 'พระครูวิสุทธาจารวิมล');
INSERT INTO `cprename` VALUES ('886', 'พระครูปภัสสราธิคุณ', 'พระครูปภัสสราธิคุณ');
INSERT INTO `cprename` VALUES ('887', 'พระครูวรสังฆกิจ', 'พระครูวรสังฆกิจ');
INSERT INTO `cprename` VALUES ('888', 'พระครูไพบูลชัยสิทธิ์', 'พระครูไพบูลชัยสิทธิ์');
INSERT INTO `cprename` VALUES ('889', 'พระครูโกวิทธรรมโสภณ', 'พระครูโกวิทธรรมโสภณ');
INSERT INTO `cprename` VALUES ('890', 'พระครูสุพจน์วราภรณ์', 'พระครูสุพจน์วราภรณ์');
INSERT INTO `cprename` VALUES ('891', 'พระครูไพโรจน์อริญชัย', 'พระครูไพโรจน์อริญชัย');
INSERT INTO `cprename` VALUES ('892', 'พระครูสุนทรคณาภิรักษ์', 'พระครูสุนทรคณาภิรักษ์');
INSERT INTO `cprename` VALUES ('893', 'พระสรภาณโกศล', 'พระสรภาณโกศล');
INSERT INTO `cprename` VALUES ('894', 'พระครูประโชติธรรมรัตน์', 'พระครูประโชติธรรมรัตน์');
INSERT INTO `cprename` VALUES ('895', 'พระครูจารุธรรมกิตติ์', 'พระครูจารุธรรมกิตติ์');
INSERT INTO `cprename` VALUES ('896', 'พระครูพิทักษ์พรหมรังษี', 'พระครูพิทักษ์พรหมรังษี');
INSERT INTO `cprename` VALUES ('897', 'พระศรีปริยัติบัณฑิต', 'พระศรีปริยัติบัณฑิต');
INSERT INTO `cprename` VALUES ('898', 'พระครูพุทธิธรรมานุศาสน์', 'พระครูพุทธิธรรมานุศาสน์');
INSERT INTO `cprename` VALUES ('899', 'พระธรรมเมธาจารย์', 'พระธรรมเมธาจารย์');
INSERT INTO `cprename` VALUES ('900', 'พระครูกิตติกาญจนวงศ์', 'พระครูกิตติกาญจนวงศ์');
INSERT INTO `cprename` VALUES ('901', 'พระครูปลัดสัมพิพัฒนวิริยาจารย์', 'พระครูปลัดสัมพิพัฒนวิริยาจารย์');
INSERT INTO `cprename` VALUES ('902', 'พระครูศีลกันตาภรณ์', 'พระครูศีลกันตาภรณ์');
INSERT INTO `cprename` VALUES ('903', 'พระครูประกาศพุทธพากย์', 'พระครูประกาศพุทธพากย์');
INSERT INTO `cprename` VALUES ('904', 'พระครูอมรวิสุทธิคุณ', 'พระครูอมรวิสุทธิคุณ');
INSERT INTO `cprename` VALUES ('905', 'พระครูสุทัศน์ธรรมาภิรม', 'พระครูสุทัศน์ธรรมาภิรม');
INSERT INTO `cprename` VALUES ('906', 'พระครูอุปถัมภ์วชิโรภาส', 'พระครูอุปถัมภ์วชิโรภาส');
INSERT INTO `cprename` VALUES ('907', 'พระครูสุนทรสมณคุณ', 'พระครูสุนทรสมณคุณ');
INSERT INTO `cprename` VALUES ('908', 'พระพรหมมุนี', 'พระพรหมมุนี');
INSERT INTO `cprename` VALUES ('909', 'พระครูสิริคุณารักษ์', 'พระครูสิริคุณารักษ์');
INSERT INTO `cprename` VALUES ('910', 'พระครูวิชิตพัฒนคุณ', 'พระครูวิชิตพัฒนคุณ');
INSERT INTO `cprename` VALUES ('911', 'พระครูพิบูลโชติธรรม', 'พระครูพิบูลโชติธรรม');
INSERT INTO `cprename` VALUES ('912', 'พระพิศาลสารคุณ', 'พระพิศาลสารคุณ');
INSERT INTO `cprename` VALUES ('913', 'พระรัตนมงคลวิสุทธ์', 'พระรัตนมงคลวิสุทธ์');
INSERT INTO `cprename` VALUES ('914', 'พระครูโสภณคุณานุกูล', 'พระครูโสภณคุณานุกูล');
INSERT INTO `cprename` VALUES ('915', 'พระครูผาสุกวิหารการ', 'พระครูผาสุกวิหารการ');
INSERT INTO `cprename` VALUES ('916', 'พระครูวชิรวุฒิกร', 'พระครูวชิรวุฒิกร');
INSERT INTO `cprename` VALUES ('917', 'พระครูกาญจนยติกิจ', 'พระครูกาญจนยติกิจ');
INSERT INTO `cprename` VALUES ('918', 'พระครูบวรรัตนวงศ์', 'พระครูบวรรัตนวงศ์');
INSERT INTO `cprename` VALUES ('919', 'พระราชพัชราภรณ์', 'พระราชพัชราภรณ์');
INSERT INTO `cprename` VALUES ('920', 'พระครูพิพิธอุดมคุณ', 'พระครูพิพิธอุดมคุณ');
INSERT INTO `cprename` VALUES ('921', 'องสุตบทบวร', 'องสุตบทบวร');
INSERT INTO `cprename` VALUES ('922', 'พระครูจันทเขมคุณ', 'พระครูจันทเขมคุณ');
INSERT INTO `cprename` VALUES ('923', 'พระครูศีลสารวิสุทธิ์', 'พระครูศีลสารวิสุทธิ์');
INSERT INTO `cprename` VALUES ('924', 'พระครูสุธรรมโสภิต', 'พระครูสุธรรมโสภิต');
INSERT INTO `cprename` VALUES ('925', 'พระครูอุเทศธรรมนิวิฐ', 'พระครูอุเทศธรรมนิวิฐ');
INSERT INTO `cprename` VALUES ('926', 'พระครูบรรณวัตร', 'พระครูบรรณวัตร');
INSERT INTO `cprename` VALUES ('927', 'พระครูวิสุทธาจาร', 'พระครูวิสุทธาจาร');
INSERT INTO `cprename` VALUES ('928', 'พระครูสุนทรวรวัฒน์', 'พระครูสุนทรวรวัฒน์');
INSERT INTO `cprename` VALUES ('929', 'พระเทพชลธารมุนี ศรีชลบุราจารย์', 'พระเทพชลธารมุนี ศรีชลบุราจารย์');
INSERT INTO `cprename` VALUES ('930', 'พระครูโสภณสมุทรคุณ', 'พระครูโสภณสมุทรคุณ');
INSERT INTO `cprename` VALUES ('931', 'พระราชเมธาภรณ์', 'พระราชเมธาภรณ์');
INSERT INTO `cprename` VALUES ('932', 'พระครูศรัทธาธรรมโสภณ', 'พระครูศรัทธาธรรมโสภณ');
INSERT INTO `cprename` VALUES ('933', 'พระครูสังฆบริรักษ์', 'พระครูสังฆบริรักษ์');
INSERT INTO `cprename` VALUES ('934', 'พระมหานายก', 'พระมหานายก');
INSERT INTO `cprename` VALUES ('935', 'พระครูโอภาสสมาจาร', 'พระครูโอภาสสมาจาร');
INSERT INTO `cprename` VALUES ('936', 'พระครูศรีธวัชคุณาภรณ์', 'พระครูศรีธวัชคุณาภรณ์');
INSERT INTO `cprename` VALUES ('937', 'พระครูโสภิตวัชรกิจ', 'พระครูโสภิตวัชรกิจ');
INSERT INTO `cprename` VALUES ('938', 'พระราชวชิราภรณ์', 'พระราชวชิราภรณ์');
INSERT INTO `cprename` VALUES ('939', 'พระครูสุนทรวรธัช', 'พระครูสุนทรวรธัช');
INSERT INTO `cprename` VALUES ('940', 'พระครูอาทรโพธิกิจ', 'พระครูอาทรโพธิกิจ');
INSERT INTO `cprename` VALUES ('941', 'พระครูวิบูลกาญจนกิจ', 'พระครูวิบูลกาญจนกิจ');
INSERT INTO `cprename` VALUES ('942', 'พระพรหมวชิรญาณ', 'พระพรหมวชิรญาณ');
INSERT INTO `cprename` VALUES ('943', 'พระครูสุพจน์วรคุณ', 'พระครูสุพจน์วรคุณ');
INSERT INTO `cprename` VALUES ('944', 'พระราชวิมลโมลี', 'พระราชาวิมลโมลี');
INSERT INTO `cprename` VALUES ('945', 'พระครูอมรธรรมนายก', 'พระครูอมรธรรมนายก');
INSERT INTO `cprename` VALUES ('946', 'พระครูพิศิษฎ์ศาสนการ', 'พระครูพิศิษฎ์ศาสนการ');
INSERT INTO `cprename` VALUES ('947', 'พระครูเมธีธรรมานุยุต', 'พระครูเมธีธรรมานุยุต');
INSERT INTO `cprename` VALUES ('948', 'พระครูปิยสีลสาร', 'พระครูปิยสีลสาร');
INSERT INTO `cprename` VALUES ('949', 'พระครูสถิตบุญวัฒน์', 'พระครูสถิตบุญวัฒน์');
INSERT INTO `cprename` VALUES ('950', 'พระครูนิเทศปิยธรรม', 'พระครูนิเทศปิยธรรม');
INSERT INTO `cprename` VALUES ('951', 'พระครูวิสุทธิ์กิจจานุกูล', 'พระครูวิสุทธิ์กิจจานุกูล');
INSERT INTO `cprename` VALUES ('952', 'พระครูสถิตย์บุญวัฒน์', 'พระครูสถิตย์บุญวัฒน์');
INSERT INTO `cprename` VALUES ('953', 'พระครูประโชติธรรมานุกูล', 'พระครูประโชติธรรมานุกูล');
INSERT INTO `cprename` VALUES ('954', 'พระเทพญาณกวี', 'พระเทพญาณกวี');
INSERT INTO `cprename` VALUES ('955', 'พระครูพิพัฒน์ชินวงศ์', 'พระครูพิพัฒน์ชินวงศ์');
INSERT INTO `cprename` VALUES ('956', 'พระครูสมุทรขันตยาภรณ์', 'พระครูสมุทรขันตยาภรณ์');
INSERT INTO `cprename` VALUES ('957', 'พระครูภาวนาวรกิจ', 'พระครูภาวนาวรกิจ');
INSERT INTO `cprename` VALUES ('958', 'พระครูศรีศาสนคุณ', 'พระครูศรีศาสนคุณ');
INSERT INTO `cprename` VALUES ('959', 'พระครูวิบูลย์ธรรมศาสก์', 'พระครูวิบูลย์ธรรมศาสก์');
